### ISSUE TITLE
Repeating Pin/UnPin A Pane Causes Error

### ISSUE THREAD

**Issue by loveemu** [vgmtrans/vgmtrans#10]
Repeating pin/unpin a pane causes an error.

Steps to reproduce:
- Un-pin Collections tab
- Re-Pin Collections tab (Coll Info tab will be stacked on Collections tab)
- Un-pin Coll Info tab
- Re-pin Coll Info tab (causes error)

Something like overlaying a tab with another one may cause an error.

**Comment by sykhro** [comment]
Closing this as WTL is essentially unmantained
