### ISSUE TITLE
Nothing showing up in Collections

### ISSUE THREAD

**Issue by Jerlewr** [vgmtrans/vgmtrans#101]

**Comment by sykhro** [comment]
Not all formats are equal. Your format is more likely just not supported. If you right click on the VGMSampColl and try to export to WAV, chances are it's just gonna be a bunch of static noise. Meaning that the program found data it couldn't recognise and treated it as raw

**Comment by Jerlewr** [comment]
The samples actually work fine. It gives me useful samples that I can tell where it would fit into the song. I could recognize the drums and the main instruments within the samples.

**Comment by Jerlewr** [comment]
In this example I did Specter Circus (https://www.youtube.com/watch?v=BhX1ha0riDk) And you can clearly here the main instrument in sample 4 (https://vocaroo.com/i/s0md5MoO5rik) and here the drum in sample 12 (https://vocaroo.com/i/s0NR7BZsp7oV).
