### ISSUE TITLE
Only giving Sample Collection

### ISSUE THREAD

**Issue by Jerlewr** [vgmtrans/vgmtrans#104]
I've put Ape Escape psf's in vgmtrans and it's only giving samples. They're actually really useful samples, but why won't it give me midi or an soundbank?

**Comment by Harley201** [comment]
With PlayStation music it's a big hit or miss, There are a lot of games that use custom music formats, for example: Crash Team Racing which won't load anything in VGMTrans. Ape Escape might have a custom format or another known format that isn't rippable yet

**Comment by Jerlewr** [comment]
Thanks.
