### ISSUE TITLE
Small Question from non programmer

### ISSUE THREAD

**Issue by RyanBram** [vgmtrans/vgmtrans#109]
Hi.
I have small questions related some parts if vgmtrans.

In the source files, I found dls and sf2 loader sources in c. My question are:

1. How usable are these sources to be used outside vgmtrans? E.g for adding dls support in fluidsynth or timidity.

2. How complete are the c sources to the specification of both formats (dls and sf2)?

Thanks.

**Comment by sykhro** [comment]
VGMTrans classes for DLS and SF2 conversion get the work done but haven't been tested for spec compliance yet. They are also not easily reusable in a different project as they depend on other VGMTrans classes.
