### ISSUE TITLE
Sequences labeled "SEQ_GS_P" in Pokemon HGSS cause a crash

### ISSUE THREAD

**Issue by Shorthorn-Studios** [vgmtrans/vgmtrans#113]
Crashes when playing GB Synth based songs using banks which only have GB synth

**Comment by loveemu** [comment]
Can you write the specific game title and the song name? That will help
developers to verify and inspect the bug later, a lot. Thanks.

**Comment by Shorthorn-Studios** [comment]
Any GB Sound music in Pokemon HGSS

**Comment by Shorthorn-Studios** [comment]
GB Sound music is labeled with a prefix like the following ("SEQ_GS_P")

**Comment by RageQuitRaccoon990** [comment]
Hey Shortthorn-Studios I need help

**Comment by Shorthorn-Studios** [comment]
yes?

**Comment by Shorthorn-Studios** [comment]
Do you need samples, midis or something for GB sounds

**Comment by sykhro** [comment]
This is a bug tracker, it's not a place for chatting. Read the readme, everything you need to know is there.

**Comment by sykhro** [comment]
Duplicate #72 , will close this one since the old one has more technical information
