### ISSUE TITLE
Hello can someone please tell me how to extract files from Cps2 it doesn't work it just extracts the green wave icon or someone make a video

### ISSUE THREAD

**Issue by RageQuitRaccoon990** [vgmtrans/vgmtrans#114]
![fuck](https://user-images.githubusercontent.com/38408898/38783699-90de8a6c-40ba-11e8-9cb8-8bab403882e1.png)

**Comment by sykhro** [comment]
If you actually read the fucking manual you would know there are no fucking midis because the format is not supported.

**Comment by Shorthorn-Studios** [comment]
It only supports .SDAT or any Nintendo DS Roms (.bin , .nds)

**Comment by RageQuitRaccoon990** [comment]
but I seen youtube description of qsound game remixes that say extracted by Vgmtrans @sykhro @Shorthorn-Studios

**Comment by loveemu** [comment]
IIRC, VGMTrans supports QSound format. You can load QSF but you probably
need to add some lines to mame.xml for Kabuki decryption, if there are no
appropriate definitions.

Sorry if I am wrong. It's out of my focus.

**Comment by RageQuitRaccoon990** [comment]
@loveemu qsf?

**Comment by RageQuitRaccoon990** [comment]
@loveemu Nevermind I tried and of course didnt work

**Comment by RageQuitRaccoon990** [comment]
@loveemu please screencap steps of doing this

**Comment by loveemu** [comment]
@RageQuitRaccoon990 Please write what files and steps you tried. They are
necessary for reproducing the problem.

Anyway I don't have a try. It's out of my focus, at least for now. Thanks.

>

**Comment by piratesephiroth** [comment]
According to the readme,  the software "knows how to unpack psf, psf2 and certain zipped mame rom sets as specified in the mame_roms.xml file". So you don't open a QSF file, but the rom itself.

I tried and some games worked, like 19xx. However avsp didn't.

**Comment by RageQuitRaccoon990** [comment]
@loveemu I tried Marvel Super Heroes CPS2 and that didnt work

**Comment by sykhro** [comment]
A bug tracker is not a support forum. Please refer to the readme: not all the games are guaranteed to work, and QSound support is experimental. Feel free to open another issue if you figure out what exactly needs to be added, or please wait for it to be implemented.
