### ISSUE TITLE
[KDT] psfs using same psflib generate the same seqs & some banks are not available (Related to a closed Issue #105)

### ISSUE THREAD

**Issue by Bakers-Avenue** [vgmtrans/vgmtrans#115]
Hi, 

I've just tried the latest commit(e3a2a54). I appreciate your consideration for the format extension.
I think that's not urgent, but there are some issues I've found regarding #105 :

1. all psfs referring same psflib generate the same(the first index of) seqs
2. I checked you've managed to get bank from CIRCUS_M, but some other banks seem not available for now.

I attached some files checked from my end for convenience. I hope it'll be helpful.
[excerpts_2.zip](https://github.com/vgmtrans/vgmtrans/files/1999214/excerpts_2.zip)

@Nisto & @loveemu
Thanks again for allowing & integrating that functionality to VGMTRANS.
I respect your priorities, so I hope you would check into them when it's okay.

**Comment by loveemu** [comment]
Extracted two VAB files manually for more research. [excerpts_2_partial_vab.zip](https://github.com/vgmtrans/vgmtrans/files/2001350/excerpts_2_partial_vab.zip)

**Comment by loveemu** [comment]
@Bakers-Avenue
Not very well tested, but I hope it will work from now.
Thank you for your detailed report. I appreciate it very much.

Please close the issue when you confirmed the fix.

**Comment by Bakers-Avenue** [comment]
@loveemu 
I've got banks/seqs from excerpt_2. Thanks for the quick resolution.
