### ISSUE TITLE
Missing file operations

### ISSUE THREAD

**Issue by sykhro** [vgmtrans/vgmtrans#116]
Currently implemented file operations in the [Qt port](https://github.com/vgmtrans/vgmtrans/tree/qt-port):
- [x] Open file dialog
- [x] Open file by drag and drop
- [x] Remove rawfiles (by shortcut)
- [x] Remove vgmfiles (by shortcut)
- [x] Context menu operations for vgmfile
- [x] Context menu operations for vgmcolls

**Comment by tommai78101** [comment]
You're missing a CMakefile, `Qt5Config.cmake`. Somehow, it's not detecting my Qt5 installation directory.

**Comment by sykhro** [comment]
If you want to use a system-wide Qt installation, I suggest you use the dedicated command prompts instead of messing with paths manually - much simpler

**Comment by tommai78101** [comment]
@sykhro 

The issue I had when following this wiki article:

https://github.com/vgmtrans/vgmtrans/wiki/Building-the-Qt-version-(alpha)

Is that I couldn't find `Qt 5.x.x 64-bit for Desktop (MSVC 2017)`, despite having a Qt 5.10 installation. I just don't like reinstalling Qt though.

**Comment by sykhro** [comment]
That's very weird though, every Qt5 installation comes with them

**Comment by tommai78101** [comment]
That's the thing... It's always weird. Thanks though.

**Comment by sykhro** [comment]
Honestly, the fact Qt5 provides cmake modules and not the way around is kinda bad. What's even the point of *finding* dependencies if you already provide a path?
I wanted to switch to Meson for compiling, but that's not gonna happen anytime soon. It would need proper backend/ui separation and we need to redesign some classes to achieve that

**Comment by tommai78101** [comment]
¯\\\_(ツ)_/¯  

Anyway, I'm just going to reinstall, because it seems like, I had something missing and I may have a corrupted Qt local installation.

**Comment by sykhro** [comment]
Completed with https://github.com/vgmtrans/vgmtrans/commit/8a9157162a7324e88a6b3eac8e0ad217f1de3fcf
