### ISSUE TITLE
Possible linux error

### ISSUE THREAD

**Issue by Bonboon228** [vgmtrans/vgmtrans#117]
Tried to compile.
Got the following message around 97 percent.
/home/bonboon228/vgmtrans/src/ui/qt/main_ui.cpp:8:10: fatal error: MainWindow.h: No such file or directory
 #include "MainWindow.h"
          ^~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/vgmtrans.dir/build.make:3817: recipe for target 'CMakeFiles/vgmtrans.dir/src/ui/qt/main_ui.cpp.o' failed
make[2]: *** [CMakeFiles/vgmtrans.dir/src/ui/qt/main_ui.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/vgmtrans.dir/all' failed
make[1]: *** [CMakeFiles/vgmtrans.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sykhro** [comment]
Issue with the file system. Please rename mainwindow.h to MainWindow.h

**Comment by sykhro** [comment]
Fixed by https://github.com/vgmtrans/vgmtrans/commit/b593d3688c51dbe10254ce43ea4508ba000abfd7
