### ISSUE TITLE
Sequences Missing in Apollo Justice: Ace Attorney DS

### ISSUE THREAD

**Issue by tj2rad10** [vgmtrans/vgmtrans#122]
In the included image I underlined (tried to underline anyway) the gaps as I saw them in the sequences.

![ajaa vgmtrans](https://user-images.githubusercontent.com/41934636/43436487-4d3bc822-944a-11e8-8f1f-c0552c89004f.PNG)

 I usually don't have to scour the entire bank but for this I scrolled through that entire bank three times I restarted VGMTrans before each try and I still haven't heard the three specific tracks I'm looking for. I'm guessing the sequences I'm looking for are most likely the "missing" ones that should appear in between the gaps? The thing is...This is the same ROM I played on my phone. I know ALL the music plays in game but every sequence for the music I hear in game isn't showing up in VGMTrans. I had created a dump of the .SSEQs using VGMToolbar and the sequences I'm looking for still aren't visible. 

I had only wanted a .mid of Apollo's objection theme (https://www.youtube.com/watch?v=VzrJP3kOngk&t=267s) and both of his pursuit themes (Normal: https://www.youtube.com/watch?v=Cofz_YxBXa0&t=291s and Variation: https://www.youtube.com/watch?v=LiJlBJramno&t=170s) from the ROM.

Any aid would be appreciated. Thank you!
More Details:
* VGMTrans version used: 1.0.0.1
* Operating System and version: Windows 10 Home, Version 1804
* Game ROM SHA-256 or music dump release name (Zophar, VGMRips, etc): 2036 - Apollo Justice - Ace Attorney (U)(Independent)

**Comment by sykhro** [comment]
It might be that those tracks simply are not sequenced. Could you go through the "Logs" tab and look for errors?

-------- Original Message --------

**Comment by sykhro** [comment]
Wait, I think I get it now. You mean that those sequences should contain what you're looking for but they never play that part, right? In that case, the track probably depends on a game variable, and vgmtrans currently doesn't handle that

**Comment by tj2rad10** [comment]
Ah well thanks anyway. I appreciate the quick response.

**Comment by sykhro** [comment]
See #41
