### ISSUE TITLE
Too much reverb in SF2 by default

### ISSUE THREAD

**Issue by jimbo1qaz** [vgmtrans/vgmtrans#123]
## Expected Behavior
Generated SF2 files currently have their reverb parameter set to 700/1000 = 70%, causing them to sound bad to me.

## Current Behavior
genList.genAmount.shAmount = 700;

## Possible Solution
genList.genAmount.shAmount = 250;

## Steps to Reproduce (for bugs)
1. Load a file.
2. Save SF2.
3. Open SF2 in foo_midi (to hear reverb) or Polyphone (to see parameters).

## Context
Listening through foo_midi (uses BASSMIDI library for reverb).

**Comment by sykhro** [comment]
70% is definitely too much, to be honest I'm not even sure this setting should be present in the first place

**Comment by sykhro** [comment]
After running some comparisons, 25% seems like an acceptable level. I'm quite sure we should default to 0 and change the reverb level based on what games actually request, but this is a good compromise for now. (I'd like to have the Qt port released before making big changes to the backend)
