### ISSUE TITLE
PS1 AKAO samples ripped at incorrect sample rate (44100hz)

### ISSUE THREAD

**Issue by nyanpasu64** [vgmtrans/vgmtrans#124]
## Expected Behavior
Sampling rate of each sample is ripped properly.

## Current Behavior
https://github.com/vgmtrans/vgmtrans/blob/098793f3aee63d5becfcc37857a3bb5c4954d440/src/main/formats/AkaoInstr.cpp#L301
Sampling rate is hardcoded to 44100, resulting in detuned and sharp samples.

## Steps to Reproduce (for bugs)
1. Load "Chrono Cross Dragon God PSF"
2. Save as MIDI and SoundFont 2.
3. Samples are detuned.

## Context
Ripping samples, using SF2 tuning information for SNES BRR tuning. Also useful for MIDI playback.

## Your Environment

* VGMTrans version used: Longstanding issue present in git master
* Operating System and version: Windows 10 x64
* Game ROM SHA-256 or music dump release name (Zophar, VGMRips, etc): ???

**Comment by jimbo1qaz** [comment]
Yet somehow, Git Master plays back the song perfectly via the toolbar Play button, with no missing samples.

**Comment by sykhro** [comment]
The WTL version uses DLS for playback, not SF2. While that 44.1k shouldn't definitely be hard-coded, the issue is probably with the SF2 conversion

**Comment by sykhro** [comment]
And indeed we have different routines for fine-tuning samples between DLS and SF2.

**Comment by jimbo1qaz** [comment]
I tried extracting DLS, then converting to SF2. Issue was still present.

**Comment by nyanpasu64** [comment]
I tried c251160 (akao-ps1 branch, not refactor). All correctly mapped samples are tuned properly, though some samples were mapped incorrectly. For some reason, it seems that every instrument is mapped to only a single sample (I don't know if that's how the samples are stored in-game).
