### ISSUE TITLE
Incorrect loop points in PS1 AKAO 

### ISSUE THREAD

**Issue by nyanpasu64** [vgmtrans/vgmtrans#125]
## Expected Behavior

Correctly ripped loop points when extracting SF2 from AKAO PSF

## Current Behavior

Many loop points are either zero, and like 10% are absurdly large integers somewhere on the order of 32 bits. The locations and values of corrupted integers changes every time I rip sf2, suggesting uninitialized memory.

## Steps to Reproduce (for bugs)

1. Load "Chrono Cross Dragon God PSF"
2. Save as MIDI and SoundFont 2.

## Context
Ripping samples, using SF2 tuning information for SNES BRR tuning. Also useful for MIDI playback.

## Your Environment

* VGMTrans version used: Git master, may be a regression from before
* Operating System and version: Windows 10 x64
* Game ROM SHA-256 or music dump release name (Zophar, VGMRips, etc): ???

**Comment by jimbo1qaz** [comment]
I tried extracting DLS, then opening in Viena. All loop points were missing.

**Comment by loveemu** [comment]
@nyanpasu64 Does the following interim build have the same issue? I couldn't confirm the problem because I felt that the shdr chunk had a sample loop point that seemed correct.

https://ci.appveyor.com/project/loveemu/vgmtrans/builds/33648641/artifacts

**Comment by nyanpasu64** [comment]
I tried c251160 (akao-ps1 branch, not refactor). The song plays properly in-app (.dls I think) and loop points appear correct when present. For some reason, it seems that every instrument is mapped to only a single sample (I don't know if that's how the samples are stored in-game).
