### ISSUE TITLE
Unable to load Professor Layton and the Unwound Future (NDS)

### ISSUE THREAD

**Issue by bridalstyle** [vgmtrans/vgmtrans#129]
vgmtrans does nothing when attempting to load the game. vgmtrans works with every other DS game I try, but not Layton and the Unwound Future. I have tried US and Europe versions.

* VGMTrans version used:  
I tried the three most recent versions as of august 2018
* Operating System and version: 
windows 7 64 bit
* Game ROM SHA-256 or music dump release name: 
5200 - Professor Layton and the Unwound Future.nds, the-eye.eu

**Comment by sykhro** [comment]
See #48
