### ISSUE TITLE
6 Errors Generated in building the Qt Version

### ISSUE THREAD

**Issue by koumal8** [vgmtrans/vgmtrans#132]
I am at the last step through building the Qt version of VGMTrans on Mac OS X 10.11.6 when these 6 errors were generated:

![schermata 2018-09-05 alle 16 57 30](https://user-images.githubusercontent.com/40038845/45102426-024cce00-b12e-11e8-94e7-a56cdd4c797f.png)

  An executable vgmtrans.app was generated, but obviously it doesn't work. It's my first time doing anything of this sort, could I get some help?

**Comment by sykhro** [comment]
You probably don't have zlib installed. Please try `brew install zlib`

**Comment by sykhro** [comment]
Any updates on this?

**Comment by koumal8** [comment]
Sorry, electric current in my house is coming and going these days; however, nothing changed, it still gives me the same exact error. I also tried installing it on an iMac with High Sierra installed and it woked fine while doing nothing different during the process.

  I run brew install zlib, deleted the vgmtrans folder and restarted the entire process; it obviously gave me a few "errors" during the first steps in that many files were already installed and when in the last step I run make the same exact errors popped up.

**Comment by sykhro** [comment]
Can you provide the output of `cmake`? (just the configuration part, where it looks for files)

**Comment by sykhro** [comment]
Any news on this?

**Comment by koumal8** [comment]
I'm really sorry to have left you hanging but I changed computer and I don't have access to the old one where I had the error :(

**Comment by sykhro** [comment]
It's alright, I'll close this one then because it seems like it got fixed with the recent cmake changes
