### ISSUE TITLE
SNES sample problems.

### ISSUE THREAD

**Issue by PotaJoe** [vgmtrans/vgmtrans#133]
So, I have been trying to rip samples from TMNT4 on SNES.
But it has bugs like:
Samples are placed wrong (voice samples as orchestra hits, breath sounds as drums, etc...)
Most songs are changed to the second time travel theme with that song's instruments.

I have no idea why this happens, and I know the SPC files are normal because I tested them all in Muki.

**Comment by sykhro** [comment]
The template you see when you open an issue isn't there as a pretty decoration, it's actually needed to be able to debug the issue.

Is it broken during playback inside program, or are you listening to exported files? Did you export DLS or SF2?

**Comment by PotaJoe** [comment]
The player AND exports both have the issue, but exports have more problems with pitching, to remake the issue, just import ANY TMNT4 .spc


________________________________

**Comment by MDHEXT** [comment]
funny, i have the same issue.

**Comment by MDHEXT** [comment]
here:


[ground theme - yoshi's island failed rip.zip](https://github.com/vgmtrans/vgmtrans/files/3006766/ground.theme.-.yoshi.s.island.failed.rip.zip)
