### ISSUE TITLE
Fatal Error when compiling in Linux Ubuntu 18.04

### ISSUE THREAD

**Issue by bryanwillis7** [vgmtrans/vgmtrans#134]
The compilation failed on linux Ubuntu 18.04 and I'm not sure what to do. Below is what my command line spit out. Any help would be greatly appreciated. I have what I thought were all the required dependencies, but perhaps there's something missing here?

```
[ 18%] Building CXX object CMakeFiles/vgmtrans.dir/src/main/Root.cpp.o
In file included from /home/bryan/vgmtrans/src/main/Root.cpp:19:0:
/home/bryan/vgmtrans/src/main/loaders/MAMELoader.h:3:10: fatal error: minizip/unzip.h: No such file or directory
 #include <minizip/unzip.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/vgmtrans.dir/build.make:389: recipe for target 'CMakeFiles/vgmtrans.dir/src/main/Root.cpp.o' failed
make[2]: *** [CMakeFiles/vgmtrans.dir/src/main/Root.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/vgmtrans.dir/all' failed
make[1]: *** [CMakeFiles/vgmtrans.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by sykhro** [comment]
minizip is a required dependency, I somehow forgot to add it to the wiki. package name should be `libminizip-dev` on ubuntu/debian

**Comment by sykhro** [comment]
also please make sure you have fluidsynth 2.0, no distribution is currently shipping it. building it is quite straightforward.

I apologize about the messy build system, but it's on the list of things to refactor for the Qt port.

**Comment by sykhro** [comment]
Yeah, ubuntu is still shipping the old Fluidsynth version.
Here's the build instructions https://github.com/FluidSynth/fluidsynth/wiki/BuildingWithCMake

vgmtrans build system was engineered to work cross-platform (Windows, macos, linux, *bsd), but as of now pretty much only works properly on linux (windows works but distributing binaries is a problem, macos broke with mojave, *bsd hasn't been tested in a while)

**Comment by sykhro** [comment]
Works on my machine™
In all seriousness, that means the cmake module to find fluidsynth is somehow broken.
Please try swapping the contents of the cmake/FindFLUIDSYNTH.cmake file with this https://raw.githubusercontent.com/Andrettin/Wyrmgus/master/cmake/modules/FindFluidSynth.cmake

I'll look into this asap

**Comment by sykhro** [comment]
Thinking about it, is lib64 the right folder on ubuntu? It might be a prefix issue

**Comment by bryanwillis7** [comment]
Tried using your file, same issue. Idk, Lib64 might not be, but I don't know what to do or how to fix that. I literally just follwed the instructions and did this:

$ cd fluidsynth-x.y.z/
$ mkdir build
$ cd build
$ cmake ..
$ sudo make install

...and on fluidsynth's end it said it worked. If there's something I did wrong there then please do let me know.

**Comment by sykhro** [comment]
Please try again with `cmake -DCMAKE_INSTALL_PREFIX="/usr" ..` when compiling fluidsynth.

**Comment by sykhro** [comment]
That's not something I can do, because that's copyrighted content. If you really can't get the Qt version to work (which is something I'll have to investigate), you can still use the Windows version with Wine.

**Comment by dustinsaunders** [comment]
Same issue exists on my Windows build with MSYS2.  Had to install the minizip dependency but still get
-- Could NOT find MiniZip (missing: MINIZIP_INCLUDE_DIR)

**Comment by dustinsaunders** [comment]
Also
`mingw-w64-fluidsynth`
didn't exist, had to use `mingw-w64-x86_64-fluidsynth`

**Comment by sykhro** [comment]
I have changed the code to be backwards-compatible with FluidSynth 1.0, since basically no one is shipping the updated version at this time. This should be solved now.
