### ISSUE TITLE
Problem opening VGMTrans_WTL.vcxproj and .sln files

### ISSUE THREAD

**Issue by topazlight** [vgmtrans/vgmtrans#136]
**EDIT:** Okay, while I would still like to learn how to fix this, I am embarrassed to report that it took me until now to realize that there are pre-built versions released periodically, so this is now far less important to me to solve.

I am attempting to build the latest version of VGMTrans as of October 22nd, 2018. My operating system is Windows 8.1 Pro, 64-bit on a x64-based processor. I am using Microsoft Visual Studio Community 2017 version 15.4.1, and my current .NET framework version is 4.7.03062.

Attempting to open VGMTrans_WTL.vcxproj or VGMTrans_WTL.sln yields the following error:

> Exception details:
> System.InvalidOperationException: Sequence contains no elements
>    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
>    at Microsoft.VisualStudio.Composition.PartDiscovery.GetElementTypeFromMany(Type type)
>    at Microsoft.VisualStudio.Composition.RuntimeComposition.RuntimeImport.get_ImportingSiteTypeWithoutCollection()
>    at Microsoft.VisualStudio.Composition.RuntimeComposition.RuntimeImport.get_IsLazy()
>    at Microsoft.VisualStudio.Composition.RuntimeComposition.RuntimeImport.get_LazyFactory()
>    at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker importingPartTracker, RuntimeImport import)
>    at Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.SatisfyImports()
>    at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.SatisfyImmediateImports()
>    at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState nextState)
>    at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState requiredState)
>    at Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
>    at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass53_0.<CreateExport>b__0()
>    at System.Lazy`1.CreateValue()
>    at System.Lazy`1.LazyInitValue()
>    at System.Lazy`1.get_Value()
>    at Microsoft.VisualStudio.Composition.ExportProvider.<>c__DisplayClass70_0`2.<GetExports>b__1()
>    at System.Lazy`1.CreateValue()
>    at System.Lazy`1.LazyInitValue()
>    at System.Lazy`1.get_Value()
>    at Microsoft.VisualStudio.Composition.ExportProvider.GetExportedValue[T]()
>    at Microsoft.VisualStudio.ComponentModelHost.ComponentModel.GetService[T]()
>    at Microsoft.Internal.VisualStudio.PlatformUI.PivotNavigatorServices.get_AttachedCollectionService()
>    at Microsoft.VisualStudio.PlatformUI.SolutionNavigatorPane.RefillNavigator()
>    at Microsoft.VisualStudio.PlatformUI.SolutionNavigatorPane.OnToolWindowCreated()
>    at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, UInt32 flags)
>    at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, ProvideToolWindowAttribute tool)
>    at Microsoft.VisualStudio.Shell.Package.FindToolWindow(Type toolWindowType, Int32 id, Boolean create, ProvideToolWindowAttribute tool)
>    at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Guid& toolWindowType, Int32 id)
>    at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsToolWindowFactory.CreateToolWindow(Guid& toolWindowType, UInt32 id)
>    at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()

I did google around for answers, but I was only able to find reports of people encountering this error with projects they themselves had created.

I'm a relative newbie to using Visual Studio to build software, so any assistance with this would be much appreciated! Thank you all very much for your time.

**Comment by topazlight** [comment]
Okay, while I would still like to learn how to fix this, I am embarrassed to report that it took me until now to realize that there are pre-built version released periodically, so this is now far less important to me to solve.

**Comment by sykhro** [comment]
I tried reproducing, it looks like you are not set up correctly for C++.
