### ISSUE TITLE
When opening the sdat for acww VGMTrans crashes

### ISSUE THREAD

**Issue by MDHEXT** [vgmtrans/vgmtrans#145]
Basically just the title

**Comment by sykhro** [comment]
There is a reason if you have a form to fill when filing a bug report. Please provide more detailed information.

**Comment by MDHEXT** [comment]
Well, that's it. VGMTrans just freezes and then stoppes entirely. There's no more information I can give you. And this only happens with the sdat file for animal crossing wild world.

**Comment by MDHEXT** [comment]
The version I was using was the 2017 interm build

**Comment by MDHEXT** [comment]
It may be a memory leak or that my computer doesn't have enough ram. It depends on how VGMTrans handles the music sequences.

**Comment by MDHEXT** [comment]
can you close this issue so that i may re-open it using your template?
