### ISSUE TITLE
MSYS2 Building trouble

### ISSUE THREAD

**Issue by Moonclair** [vgmtrans/vgmtrans#149]
**Build environment details**
Followed the wiki instructions? Yes
Operating system: Win 10 Pro - Build 1809
CMake version:  cmake version 3.14.4
libfluidsynth version: FluidSynth executable version 2.0.5
Qt version:  Qt 5.12.2 
VGMTrans commit being built: Latest

I think that I Couldn't find the right log. I found CMakeCache and CMakeOutput. There's no CMakeError

**Failure details**
Please provide details about the error. Include any custom CMake flags if you have added them. 

Hi i carefully followed the instructions, I researched for solutions and tried installing a lot of packages, trying various shells. Then reinstalled all and start over again. I think i'm kinda blind respect to the solution

` Moonclair@Seba MINGW64 ~/vgmtrans/build
$ cmake -G "MSYS Makefiles" ..
-- Using system Zlib 1.2.11
-- Could NOT find MiniZip (missing: MINIZIP_LIBRARIES MINIZIP_INCLUDE_DIR)
-- Using static MiniZip fallback
-- Could NOT find TINYXML (missing: TINYXML_LIBRARIES TINYXML_INCLUDE_DIR)
-- Using static TinyXML fallback
-- Using system Qt 5.12.2
-- Using system FluidSynth 2.0.5
-- Configuring done
-- Generating done
-- Build files have been written to: D:/msys64/home/Moonclair/vgmtrans/build

Moonclair@Seba MINGW64 ~/vgmtrans/build
$ make -j$(nproc)
[  3%] Built target tinyxml_static
[  5%] Built target minizip
[  6%] Automatic MOC for target vgmtrans
[  6%] Built target vgmtrans_autogen
[  6%] Building CXX object CMakeFiles/vgmtrans.dir/src/main/Root.cpp.obj
[  7%] Building CXX object CMakeFiles/vgmtrans.dir/src/main/VGMFile.cpp.obj
[  7%] Building CXX object CMakeFiles/vgmtrans.dir/src/main/VGMInstrSet.cpp.obj
[  8%] Building CXX object CMakeFiles/vgmtrans.dir/src/main/VGMItem.cpp.obj
[  8%] Building CXX object CMakeFiles/vgmtrans.dir/src/main/VGMMiscFile.cpp.obj
[  9%] Building CXX object CMakeFiles/vgmtrans.dir/src/main/VGMMultiSectionSeq.cpp.obj
[  9%] Building CXX object CMakeFiles/vgmtrans.dir/src/main/VGMRgn.cpp.obj
[ 10%] Building CXX object CMakeFiles/vgmtrans.dir/src/main/VGMSamp.cpp.obj
In file included from D:/msys64/home/Moonclair/vgmtrans/src/main/Root.cpp:19:
D:/msys64/home/Moonclair/vgmtrans/src/main/loaders/MAMELoader.h:3:10: fatal error: minizip/unzip.h: No such file or directory
 #include <minizip/unzip.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/vgmtrans.dir/build.make:262: CMakeFiles/vgmtrans.dir/src/main/Root.cpp.obj] Error 1
make[2]: *** Se espera a que terminen otras tareas....
make[1]: *** [CMakeFiles/Makefile2:75: CMakeFiles/vgmtrans.dir/all] Error 2
make: *** [Makefile:84: all] Error 2`

Thank you in advance for your time

[CMakeCache.txt](https://github.com/vgmtrans/vgmtrans/files/3226599/CMakeCache.txt)
[CMakeLists.txt](https://github.com/vgmtrans/vgmtrans/files/3226601/CMakeLists.txt)

**Comment by sykhro** [comment]
Could you please try again with https://github.com/sykhro/vgmtrans?
The fixes there should be backported eventually

**Comment by Moonclair** [comment]
Thanks for your quickly answer. I'll do it right now

**Comment by sykhro** [comment]
No problem. If you encounter issues with that, please open an issue in the tracker of that repository
