### ISSUE TITLE
CPS3 support

### ISSUE THREAD

**Issue by insertsurnamehere** [vgmtrans/vgmtrans#150]
Hello, 
i'm a frequent user of vgmtrans, as it is, in my opinion, the most user friendly music ripper on the internet, and appreciate all the effort put int this project.
I also like the ammount of music formats supported by it.
i come from vgmrips, because an user by the name of Mike77154, wich asked me on including, or take inspiration from my cps3 ripper, which i worked on with great help from superctr and ValleyBell, at march 5th.

A direct link to the forum post: https://vgmrips.net/forum/viewtopic.php?f=15&t=2873&start=45#p10611
and my github, to "validate" my somewhat ambitious claim
https://github.com/insertsurnamehere/cps32midi/blob/master/main.c

I wanted to know two things:

first, if whoever made this post can associate himself to the vgmtrans project,

and second, if it cloud be possible to "include" this basic (and clunky to use) cps3 ripper, of course after the refracting period your project is going under.

You can contact valleybell for confirmation

**Comment by sykhro** [comment]
I believe the user is @mikelow 

As for adding the new ripper, PRs are welcome. I'm currently taking care of merging the work of the qt-port and ui_refactor branches, and given the amount of work I don't see myself adding any new "feaure" code anytime soon

**Comment by insertsurnamehere** [comment]
Oh, ok, i'll wait here.
I cloudn't get the project done, because i was, let's just say, tired of it, and i couldn't see myself finishing this project anytime soon, and developement was heavelly slowed down

**Comment by mikelow** [comment]
I'm not the user on that form and wasn't aware of the work on cps3, but by coincidence, I did my own cps3 work a while back (along with cps1). I believe it's accessible on the ui_refactor branch. It only works with the non chd version of mame roms.

**Comment by insertsurnamehere** [comment]
Ok, i wanted some confirmation either way, im left to wonder the real intentions of that user.

The fact that you also worked on something cps3 related makes me fell slightly bested.

**Comment by insertsurnamehere** [comment]
Anyway, should i close the issue now, or leave it like this until the cps3 ripper is implemented?

**Comment by Mike77154** [comment]
@insertsurnamehere  hello there, Im Mike77154, man, I am the guy who talk about adding cps3 support  on Vgmtrans

**Comment by Mike77154** [comment]
@insertsurnamehere The thing is for example on the new Sample data points on Cps3 games, but, how do you get the data, do you use OpenMPT?

**Comment by Mike77154** [comment]
Talking about Vgm trans and Cps1 roms, @mikelow  I was messing around the Cps1 data pcm, and maybe we can add a support for Segapcm (Model X and Model Y) and OKiM6295 from cps1 for get some soundfonts

**Comment by sykhro** [comment]
We can say that this is officially in progress I guess

**Comment by mikelow** [comment]
> We can say that this is officially in progress I guess

More than that, I'd say it's supported. Closing this, though I should have done so earlier as its a feature request.
