### ISSUE TITLE
Wrong instruments in .DLS/.SF2

### ISSUE THREAD

**Issue by Wanny** [vgmtrans/vgmtrans#152]
**Describe the bug**
With some games the DLS/SoundFont output is completely messed up

**To Reproduce**
Example, with SSF2 Turbo:
1. Load the game
2. Rip 1st track (Ken's stage)
3. Open the MIDI with its corresponding DLS/.sf2 (quickest way is to use AIMP, that has an integrated SoundFont loader)
4. Press Play and prepare to suffer. 
EDIT: oddly enough, only the melodic instruments are incorrect. The drums are fine.

**Expected behavior**
Uh... to have the right instruments.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - VGMTrans version: 20170225-129-gab2cf9f
 - VGMTrans log: (how do I export it? in any case it doesn't show any error)
 - Game ROM or music dump SHA-256: 
ssf2t.zip: 28EF8582A4721766646C2475A26CE15932E53907C4924821E02D67B089A36AC7

**Comment by qsie** [comment]
Can reproduce with Kirby's Dreamland 3. VLC plays .SFC properly, but plays and exports incorrect data through VGMTrans.

- OS: Windows 10 x64
- VGMTrans version: interim-20170225
- VGMTrans log: No errors
- Game ROM or music dump SHA-256: 18 Sand Canyon 1.spc: 3DD1287F67351A18422570F311F196564FBCA259402CD49C3933DA2510FEA7BC

**Comment by emjzero2** [comment]
Same thing happens with some of FFX's tracks

**Comment by korobetski** [comment]
> 
> 
> Same thing happens with some of FFX's tracks

Midi format can handle up to 16 channels with the channel 10 reserved to drums.
Akao's format is different (as i know from Vagrant Story) and can handle up to 32 tracks. When you try to transcode Akao's instructions into midi, make sure the same instruments (midi PC) use the same channel when your Akao file have more than 16 tracks.

See here : https://github.com/korobetski/Vagrant-Story-Unity-Parser/blob/master/Assets/VS/Parser/AKAO/AKAOComposer.cs  ->  SyncTracksChannels() function to reorder tracks channels.

In the original game, i tend to think that each track was synthetized separatly.

**Comment by emjzero2** [comment]
FFX does not use akao's format they are BGM for sequence and WD for soundfont

**Comment by loveemu** [comment]
If I understood the problem correctly, the problem with SSF2 Turbo has been fixed.
