### ISSUE TITLE
Club Penguin DS games .voxadpcm file support

### ISSUE THREAD

**Issue by noddy360** [vgmtrans/vgmtrans#154]
**Is your feature request related to a problem? Please describe.**
Hi. I tried to open both Club Penguin games for the Nintendo DS, they only detected the Dgamer related data, and not the main game data. Club Penguin: Elite Penguin Force and its sequel Herbert's Revenge have its main sound data stored in a .bin format. The sound files for both games are called music.bin and sfx.bin respectively. I've been trying to access these files for years, trying different methods to view its contents, but I've always failed.

**Describe the solution you'd like**
I would like to access these files finally and be able to extract its samples just like any other DS game.
**Additional context**
These are some rather unique .bin files. You can't view them as they were a disk image. You can't view them using a ds file extractor either. The only thing you can do is view the file via a hex editor. Both files are inside a "sound" folder inside the ROM.

I do know there was an attempt at understanding the format: https://gbatemp.net/threads/club-penguin-music-files-help.496934/
Theres also a cheat code where you can change the music in both games. The sequel has unused music tracks it seems: https://tcrf.net/Club_Penguin:_Elite_Penguin_Force:_Herbert%27s_Revenge#Unused_music

**Comment by noddy360** [comment]
Ok, so I want to bring an update to this.
People have finally been able to rip these files and access them...
However, that brings another issue. When ripping the audio files, it now brings some .voxadpcm files and the only way to open them is through an obscure audio editing program. Is there a way to access them without it or is there a way to convert them to standard DS audio files I wonder.

**Comment by sykhro** [comment]
By the extension name that looks like a Digital ADPCM file, which are usually used for telephony. I'm guessing they might have used that to store samples but with some tweaks.
By a quick glance this seems nothing like the standard NDS format

**Comment by sykhro** [comment]
We already have an issue for tracking club penguin format research, closing this
