### ISSUE TITLE
Only saving wav files

### ISSUE THREAD

**Issue by matmanf** [vgmtrans/vgmtrans#160]
**Describe the bug**
I've tried to drag different rom I have but the only possible action from the right click mouse menu is to save it as wav.

**To Reproduce**
I do all the steps as written in the guide

**Desktop (please complete the following information):**
 - OS: OSX Catilina

 - Game ROM : I tried Bam Stoke's Dracula and Bubba 'N' Stix

**Comment by sykhro** [comment]
It most likely means those formats are not supported.
> Bam Stoke's Dracula
For which console?
> Bubba 'N' Stix
That one is definitely not supported. VGMTrans doesn't handle .vgm besides CPS-2 (and a very limited subset of it)

**Comment by matmanf** [comment]
Oh well, thank you anyway sir

Matteo Manfellotti
matteomanfellotti@icloud.com
