### ISSUE TITLE
Can't open all SSEQ files

### ISSUE THREAD

**Issue by Nonchalantree** [vgmtrans/vgmtrans#161]
**Describe the bug**
Not all SSEQ files that exist on my Spirit Tracks ROM will open on VGMTrans 
(I used Tinke to confirm that they do in fact exist and are usable)
(There is other SoundData missing, but has not caused problems as far as I know)

**To Reproduce**
Steps to reproduce the problem.
1. Open VGMTrans
2. Open Spirit Tracks ROM through VGMTrans

**Expected behavior**
SSEQ files will open and work as expected

**Desktop:**
 - OS: Windows
 - VGMTrans Interim Build (2017-02-25)

**Comment by sykhro** [comment]
Please try again using the build in the refactor branch and attaching the log

**Comment by Nonchalantree** [comment]
Forgive me, I am still quite new to GitHub, do you mean in "Projects" where it says "Refactor and Cleanup"? If it is, I do not know how to add to it. 
Otherwise, I do not know where the refactor branch is.

**Comment by sykhro** [comment]
You can find it [here](https://github.com/vgmtrans/vgmtrans/actions/runs/68301946)

**Comment by sykhro** [comment]
Any updates on this?

**Comment by sykhro** [comment]
Closing due inactivity
