### ISSUE TITLE
FFVI - wrongly assigned MIDI instruments, faulty drum track

### ISSUE THREAD

**Issue by ElSaico** [vgmtrans/vgmtrans#165]
**Describe the bug**
When exporting a Final Fantasy VI music to mid+sf2, it assigns the wrong instruments to its tracks; plus, several of them seem to have one drum track that doesn't map to any instrument properly.

VGMTrans itself plays the original file correctly.

**To Reproduce**
Steps to reproduce the problem.
1. Load a .spc file from FFVI (let's use Dancing Mad (part 5) for this report)
2. Export to MIDI and SoundFont 2
3. Import the .mid file in an editor such as MuseScore
4. Load the .sf2 file in the same editor
5. Play

**Expected behavior**
Music plays inside the editor just like in VGMTrans or any SPC player.

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - VGMTrans version: f07636ce
 - VGMTrans log: the application doesn't seem to log anything at all on macOS?
 - Game ROM or music dump SHA-256: 856797bee711ad67e1b697dd97b5c6b603650f7f2273cebfd3b74bcff63f801b

**Additional context**
The correct instrument assignment for the aforementioned music should be:

1. 0x20 / num 32
1. 0x20 / num 32
1. 0x22 / num 34
1. ??? (0x26 / num 38 comes closer)
1. 0x21 / num 33 
1. 0x24 / num 36
1. 0x21 / num 33
1. 0x23 / num 35

**Comment by sykhro** [comment]
> VGMTrans itself plays the original file correctly.
What you hear is what you export, the application uses FluidSynth for playback. Have you tried any other way to play the file besides MuseScore?

**Comment by ElSaico** [comment]
Hmm... it seems that it does work correctly under VLC + FluidSynth. This means the MuseScore importer is acting a bit funky[1], I guess.

So, since VGMTrans is innocent in all this, I'm closing it.

[1] Since the reason I'm doing all this in the first place is to play some bass lines, I must note that it's not the *good* kind of funky.
