### ISSUE TITLE
VGMTrans Assertion Failed?

### ISSUE THREAD

**Issue by PuertoMK** [vgmtrans/vgmtrans#167]
**Describe the bug**
when I downloaded the latest version of VGMTrans I opened it and tried to import my brsar from Mario Kart Wii in hopes to export the wifi music, the content's load up just I can't export the SEQ or any other ones if I try to export them as midi and dls crashes same goes with the midi and sound font 2 option, oh even trying to export the contents of the SEQ also gives me the same error
**To Reproduce**
Steps to reproduce the problem.
1. Load the program
2. Load up the .brsar file
3. click on the file like SEQ then try to export it, but for me it just gave me some Visual C++ error

**Expected behavior**
I expect it to at least export the game files to another format 

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 1809
 - VGMTrans 1.0.62
 - VGMTrans log 1.0.63
 - Game ROM or music dump SHA-256

**Additional context**
None
![vgmtranshelp](https://user-images.githubusercontent.com/56810384/82094300-c4f25f00-96ca-11ea-8ebb-c883dc2030e3.jpg)

**Comment by sykhro** [comment]
VGMTrans doesn't have Wii support, you're probably using some random fork which we have no control over
