### ISSUE TITLE
[FEATURE REQ] Add Instrument Support for MP2k

### ISSUE THREAD

**Issue by loveemu** [vgmtrans/vgmtrans#17]
I would be happy if VGMTrans supported MP2kInstrSet.

A program called GBAMusRiper does MP2k to SF2 conversion. Every technical things can be referred from it.
http://www.romhacking.net/utilities/881/

**Comment by mikelow** [comment]
@sykhro 
Oh, I see now that you _just_ added this to Format support. I placed it in the Done column. Feel free to correct.

Perhaps we should change the name of the "Done" column, as I don't consider any format 100% Done. But some are very "Well Supported".

**Comment by sykhro** [comment]
> @sykhro Oh, I see now that you _just_ added this to Format support. I placed it in the Done column. Feel free to correct.
> 
> Perhaps we should change the name of the "Done" column, as I don't consider any format 100% Done. But some are very "Well Supported".

I have selected all labels under `format:unimplemented` and moved them to the `todo` column of "Format support". I'm trying to reorganize issues a bit to see if there's anything that can realistically get fixed easily
