### ISSUE TITLE
Crashed when trying to play certain music

### ISSUE THREAD

**Issue by KevinMei-Github** [vgmtrans/vgmtrans#171]
**Describe the bug**
When trying to play a music from the extracted sound_data.sdat from Pokemon White 2 US, the program crashed without any message.

**To Reproduce**
1. Open vgmtrans and open the file I extracted. It can be found here https://github.com/KevinMei-Github/Shared-Files/tree/master/W2_sdat (The file was splited both in rar and zip format)
2. Select SEQ_BGM_OPENING_TITLE_B and play it. Ta-da! It crashed.

**Expected behavior**
Clearly it should play the music I selected.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VGMTrans version: The latest one on AppVeyor.
 - VGMTrans log: Where's the log? I cannot find it.
 - SHA-256 (sdat file): 8f084abcafa0972ba9374d39e57be6b56aab8be24de9e1e27b57a09b7446babe

**Comment by sykhro** [comment]
Fixed by bf343f8b0906d94e75f7d7850c45065fda960f7c
