### ISSUE TITLE
Could not compile, "fatal: could not create work tree dir 'vgmtrans': Permission denied"

### ISSUE THREAD

**Issue by Hefaustas** [vgmtrans/vgmtrans#172]
Hello, I've been trying to compile the qt version of VGMTrans, but I've got an issue.

I installed the Visual Studio Build Tools 2019, and when then I tried to run the command `git clone -b refactor --recursive https://github.com/vgmtrans/vgmtrans` on the Visual Studio Commmand Prompt I got this error message `fatal: could not create work tree dir 'vgmtrans': Permission denied`. Is there any way to fix that?

**Comment by sykhro** [comment]
You probably lack permissions to make a folder in that folder

**Comment by Hefaustas** [comment]
Ohhhhh, I see. I don't use github that much and I haven't exactly figured out how it fully works yet. Is there any way I can compile the code into a usable program?

**Comment by sykhro** [comment]
You can download a compiled version [here](https://github.com/vgmtrans/vgmtrans/actions/runs/105933220)

**Comment by Hefaustas** [comment]
Oh thanks, excuse me for not knowing that.
