### ISSUE TITLE
[NDS] Incorrect loop point or missing sections for Phantasy Star 0

### ISSUE THREAD

**Issue by coderkei** [vgmtrans/vgmtrans#174]
**Describe the bug**
When loading the game Phantasy Star 0, some songs appear to have an incorrect loop point and stop prematurely. In the game Phantasy Star 0, the track SEQ_BGM_CHARA for example should be 2:42 long but the midi extraction or the playback (from timing it) is only 1:29 long and stops too early. After 1:29 the game normally loops but plays a slightly different melody.

**To Reproduce**
Steps to reproduce the problem.
1. Load the game Phantasy Star 0
2. Play SEQ_BGM_CHARA or export it to Midi, the bug is the same.

**Expected behavior**
The full song to play and loop correctly and not a shortened version.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VGMTrans version: VGMTrans Interim Build (2017-02-25).
 - Game ROM or music dump SHA-256: Phantasy Star 0 (US Release). SHA-256 Hash: C47057DA51DE3FEC99C041FF0390F82A15D1A825601AF876428FC29B47498357

**Additional context**
I also tried the latest appveyor build (vgmtrans-interim-20170225-47-g1474e06-akao-ps1-116-vs2015-Win32-Release)
However the bug was still present and this time some instruments would not play correctly near the loop point.

**Comment by sykhro** [comment]
This is likely another case of #41
