### ISSUE TITLE
FindFLUIDSYNTH.cmake picks the correct headers but the wrong library when both major versions are installed

### ISSUE THREAD

**Issue by TheGag96** [vgmtrans/vgmtrans#177]
**Build environment details**
Followed the wiki instructions? yes
Operating system: elementary OS  5.1.6 Hera (based on Ubuntu 18.04)
CMake version: 3.18.0 (had to use a PPA to get it)
libfluidsynth version: 2.1.4 (just built from source)
Qt version: 5.9.5
VGMTrans commit being built: c3e1222 (latest on `refactor` branch, tried some commits back but basically the same issue)
Please provide the full CMake log (the one that gets generated when you do `cmake ..`).
[Here.](https://pastebin.com/YB703hzT)

**Failure details**

The main error:

```
CMakeFiles/vgmtrans.dir/MusicPlayer.cpp.o: In function `MusicPlayer::makeSynth()':
MusicPlayer.cpp:(.text+0x26b): undefined reference to `fluid_sfloader_set_callbacks'
CMakeFiles/vgmtrans.dir/MusicPlayer.cpp.o: In function `MusicPlayer::Seek(int)':
MusicPlayer.cpp:(.text+0x464): undefined reference to `fluid_player_seek'
collect2: error: ld returned 1 exit status
src/vgmtrans-qt/CMakeFiles/vgmtrans.dir/build.make:885: recipe for target 'src/vgmtrans-qt/vgmtrans' failed
make[2]: *** [src/vgmtrans-qt/vgmtrans] Error 1
CMakeFiles/Makefile2:471: recipe for target 'src/vgmtrans-qt/CMakeFiles/vgmtrans.dir/all' failed
make[1]: *** [src/vgmtrans-qt/CMakeFiles/vgmtrans.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
make: *** [all] Error 2
```

Any ideas? Thanks!

**Comment by sykhro** [comment]
Mh, this will take some time to figure out.
Can you confirm "/usr/lib/x86_64-linux-gnu/libfluidsynth.so" is indeed FluidSynth 2.1.4?

**Comment by TheGag96** [comment]
Ah... I think it wasn't, actually...! I had libfluidsynth1 installed (needed by a good number of packages, like ardour, libsdl2-mixer, etc.) and had attempted to build and install fluidsynth on top. Unfortunately, doing that simply put 2.1.4 in `/usr/lib`, whereas `/usr/lib/x86_64-linux-gnu/` actually held 1.0. I had to temporarily uninstall libfluidsynth1 (and thus its dependents), and then building vgmtrans worked fine.

Is there any way to reconcile having both FS 1.0 and 2.0 on the same machine?

**Comment by sykhro** [comment]
> Is there any way to reconcile having both FS 1.0 and 2.0 on the same machine?
Our script that looks for fluidsynth should be able to pick the correct version, I'll have to test it personally but there might be some pkgconf trickery going on here

**Comment by io7m** [comment]
Is there a way in `cmake` to be more specific about the `fluidsynth` version in general? I've just tried to build `vgmtrans` on Arch Linux using `fluidsynth 2.1.5` and although `cmake` succeeds, the actual build fails:

```
[  2%] Building CXX object CMakeFiles/vgmtrans.dir/src/ui/qt/MusicPlayer.cpp.o
In file included from /home/rm/git/com.github/vgmtrans/vgmtrans/src/ui/qt/MusicPlayer.cpp:9:
/home/rm/git/com.github/vgmtrans/vgmtrans/lib/fluidsynth/mem_sfloader/mem_sfloader.h:534:20: error: field ‘iter_preset’ has incomplete type ‘fluid_preset_t’ {aka ‘_fluid_preset_t’}
  534 |     fluid_preset_t iter_preset;
      |                    ^~~~~~~~~~~
In file included from /usr/include/fluidsynth.h:95,
                 from /home/rm/git/com.github/vgmtrans/vgmtrans/src/ui/qt/MusicPlayer.h:5,
                 from /home/rm/git/com.github/vgmtrans/vgmtrans/src/ui/qt/MusicPlayer.cpp:6:
/usr/include/fluidsynth/types.h:41:16: note: forward declaration of ‘fluid_preset_t’ {aka ‘struct _fluid_preset_t’}
   41 | typedef struct _fluid_preset_t fluid_preset_t;                  /**< SoundFont preset */
      |                ^~~~~~~~~~~~~~~
In file included from /home/rm/git/com.github/vgmtrans/vgmtrans/src/ui/qt/MusicPlayer.cpp:9:
/home/rm/git/com.github/vgmtrans/vgmtrans/lib/fluidsynth/mem_sfloader/mem_sfloader.h:601:5: error: ‘fluid_gen_t’ does not name a type; did you mean ‘fluid_real_t’?
  601 |     fluid_gen_t gen[GEN_LAST];
      |     ^~~~~~~~~~~
      |     fluid_real_t
/home/rm/git/com.github/vgmtrans/vgmtrans/lib/fluidsynth/mem_sfloader/mem_sfloader.h:640:5: error: ‘fluid_gen_t’ does not name a type; did you mean ‘fluid_real_t’?
  640 |     fluid_gen_t gen[GEN_LAST];
      |     ^~~~~~~~~~~
      |     fluid_real_t
/home/rm/git/com.github/vgmtrans/vgmtrans/src/ui/qt/MusicPlayer.cpp: In constructor ‘MusicPlayer::MusicPlayer()’:
/home/rm/git/com.github/vgmtrans/vgmtrans/src/ui/qt/MusicPlayer.cpp:44:49: error: ‘FLUID_REVERB_DEFAULT_WIDTH’ was not declared in this scope
   44 |         fluid_synth_set_reverb(synth, 0.5, 0.8, FLUID_REVERB_DEFAULT_WIDTH, 0.3);
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/vgmtrans.dir/build.make:2054: CMakeFiles/vgmtrans.dir/src/ui/qt/MusicPlayer.cpp.o] Error 1
make[2]: Leaving directory '/home/rm/git/com.github/vgmtrans/vgmtrans/build'
make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/vgmtrans.dir/all] Error 2
make[1]: Leaving directory '/home/rm/git/com.github/vgmtrans/vgmtrans/build'
make: *** [Makefile:103: all] Error 2
make: Leaving directory '/home/rm/git/com.github/vgmtrans/vgmtrans/build'
```

**Comment by sykhro** [comment]
> Is there a way in `cmake` to be more specific about the `fluidsynth` version in general? I've just tried to build `vgmtrans` on Arch Linux using `fluidsynth 2.1.5` and although `cmake` succeeds, the actual build fails:
> 
> ```
> [  2%] Building CXX object CMakeFiles/vgmtrans.dir/src/ui/qt/MusicPlayer.cpp.o
> In file included from /home/rm/git/com.github/vgmtrans/vgmtrans/src/ui/qt/MusicPlayer.cpp:9:
> /home/rm/git/com.github/vgmtrans/vgmtrans/lib/fluidsynth/mem_sfloader/mem_sfloader.h:534:20: error: field ‘iter_preset’ has incomplete type ‘fluid_preset_t’ {aka ‘_fluid_preset_t’}
>   534 |     fluid_preset_t iter_preset;
>       |                    ^~~~~~~~~~~
> In file included from /usr/include/fluidsynth.h:95,
>                  from /home/rm/git/com.github/vgmtrans/vgmtrans/src/ui/qt/MusicPlayer.h:5,
>                  from /home/rm/git/com.github/vgmtrans/vgmtrans/src/ui/qt/MusicPlayer.cpp:6:
> /usr/include/fluidsynth/types.h:41:16: note: forward declaration of ‘fluid_preset_t’ {aka ‘struct _fluid_preset_t’}
>    41 | typedef struct _fluid_preset_t fluid_preset_t;                  /**< SoundFont preset */
>       |                ^~~~~~~~~~~~~~~
> In file included from /home/rm/git/com.github/vgmtrans/vgmtrans/src/ui/qt/MusicPlayer.cpp:9:
> /home/rm/git/com.github/vgmtrans/vgmtrans/lib/fluidsynth/mem_sfloader/mem_sfloader.h:601:5: error: ‘fluid_gen_t’ does not name a type; did you mean ‘fluid_real_t’?
>   601 |     fluid_gen_t gen[GEN_LAST];
>       |     ^~~~~~~~~~~
>       |     fluid_real_t
> /home/rm/git/com.github/vgmtrans/vgmtrans/lib/fluidsynth/mem_sfloader/mem_sfloader.h:640:5: error: ‘fluid_gen_t’ does not name a type; did you mean ‘fluid_real_t’?
>   640 |     fluid_gen_t gen[GEN_LAST];
>       |     ^~~~~~~~~~~
>       |     fluid_real_t
> /home/rm/git/com.github/vgmtrans/vgmtrans/src/ui/qt/MusicPlayer.cpp: In constructor ‘MusicPlayer::MusicPlayer()’:
> /home/rm/git/com.github/vgmtrans/vgmtrans/src/ui/qt/MusicPlayer.cpp:44:49: error: ‘FLUID_REVERB_DEFAULT_WIDTH’ was not declared in this scope
>    44 |         fluid_synth_set_reverb(synth, 0.5, 0.8, FLUID_REVERB_DEFAULT_WIDTH, 0.3);
>       |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
> make[2]: *** [CMakeFiles/vgmtrans.dir/build.make:2054: CMakeFiles/vgmtrans.dir/src/ui/qt/MusicPlayer.cpp.o] Error 1
> make[2]: Leaving directory '/home/rm/git/com.github/vgmtrans/vgmtrans/build'
> make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/vgmtrans.dir/all] Error 2
> make[1]: Leaving directory '/home/rm/git/com.github/vgmtrans/vgmtrans/build'
> make: *** [Makefile:103: all] Error 2
> make: Leaving directory '/home/rm/git/com.github/vgmtrans/vgmtrans/build'
> ```

You are not building the correct branch, checkout `refactor` and try again

**Comment by io7m** [comment]
Yep, you're right! Sorry for the noise.

**Comment by sykhro** [comment]
Is this still an issue with the current `master`?

**Comment by sykhro** [comment]
Closing as this shouldn't be happening anymore with the latest commit.
