### ISSUE TITLE
HOSAInstrSet: Unable To Export DLS From Dewprism PSF

### ISSUE THREAD

**Issue by loveemu** [vgmtrans/vgmtrans#18]
When VGMTrans loads Dewprism PSF, it fails to load HOSAInserset::sampColl. As a result, it fails to export DLS/SF2.

**Comment by loveemu** [comment]
Apparently, it simply wasn't supported. I finally noticed that after I understand how to improve the loader. I am crying and going to close the issue.

**Comment by AceKombat** [comment]
Hmm? I'm guessing it has to do with certain songs of Dewprism. Getting soundfont from it in older versions of VGMTrans was definitely possible.
