### ISSUE TITLE
Qt does not follow system theme

### ISSUE THREAD

**Issue by caleb39411** [vgmtrans/vgmtrans#183]
**Describe the bug**
In any desktop environment with a Qt theme set, in this case, KDE Plasma on Linux, the application does not follow the theme despite it being written in Qt. I am not sure if this is a bug or intended behaviour, but I have not encountered another Qt application that exhibits the same behaviour.

**To Reproduce**
Steps to reproduce the problem.
Open the Qt version.

**Expected behavior**
The application should use the Qt theme set, if any.

**Desktop (please complete the following information):**
 - OS: Manjaro 20.10
 - Version 2017/02/25
 - VGMTrans log - empty
 - Game ROM or music dump SHA-256 - N/A

**Comment by caleb39411** [comment]
The program does however use the set icon theme, leading me to believe this is unintended.

**Comment by sykhro** [comment]
This is actually intended, [the theme we use](https://github.com/randrew/phantomstyle) is lighter and less buggy compared to the defaults that Qt ships. We just set a custom color palette, but that could be removed to use the system colors.

**Comment by sykhro** [comment]
Or better, an option to choose which one; our color scheme was made to match the icons exactly, we also have a light one but haven't implemented a switch for it yet

**Comment by caleb39411** [comment]
It would be good then if Qt theme is set, it be followed, as the icon set does as such; the icon theme used is that of the system.

**Comment by sykhro** [comment]
The Qt port in `master` (which is what will be officially supported from now on) now follows the system theme.
We're not bothering with system icons, as there is no standard way to fetch them for all platforms. Qt seems to be offering only options for X11.

However, all of our icons are SVG, so something could be implemented to color-correct them if they don't have enough contrast with the system theme.
