### ISSUE TITLE
Can't even begin process to compile a build

### ISSUE THREAD

**Issue by edale2** [vgmtrans/vgmtrans#185]
**Build environment details**
Followed the wiki instructions? yes
Operating system: Win 10

**Failure details**
I followed wiki https://github.com/vgmtrans/vgmtrans/wiki/Building-the-Qt-version#vs-noide directions on how build the Windows version.

I installed Build Tools for Visual Studio from the provided link. 

I ran "x64 Native Tools Command Prompt for VS 2019".

I entered `git clone -b refactor --recursive https://github.com/vgmtrans/vgmtrans`.

I got the following message:
`'git' is not recognized as an internal or external command,
operable program or batch file.`

So... I can't even get past step 1 in making a build of this, and the copies in the releases section looks to be several years out of date...

Please help. Either in figuring out how to do this myself, or in making a current build and getting me a link to grab it.

**Comment by sykhro** [comment]
You're missing git, which can be installed from the VS installer. Anyway, latest builds are [here](https://github.com/vgmtrans/vgmtrans/actions).
Keep in mind that bug trackers are not support forums.

**Comment by edale2** [comment]
![Untitled](https://user-images.githubusercontent.com/20962345/99959924-e4450580-2d59-11eb-87f2-c17f4de00919.png)
So where exactly did I miss the option that installs the git command? As far as I can tell I've installed everything in the VS installer, and I don't have the git command, which means something else needs to be installed that's not listed in the wiki's directions.

I'd view _that_ as relevant to a bug tracker, as it means there's an error in the instructions.

**Comment by piratesephiroth** [comment]
I guess it's not enabled by default.

![image](https://user-images.githubusercontent.com/10672233/99961519-58d56f80-2d6d-11eb-9bb3-4b02a386ff53.png)

**Comment by edale2** [comment]
![Untitled](https://user-images.githubusercontent.com/20962345/99963344-a5b24980-2d5f-11eb-920a-db78f6dd2960.png)
Hmmm... It's not an option in Build Tools, looks like that's the enterprise version in your screenshot...

At any rate, I found git at:
https://git-scm.com/download/win

And everything seems to be working in the build process now.
