### ISSUE TITLE
Instructions for windows Qt build not full.

### ISSUE THREAD

**Issue by ekatris** [vgmtrans/vgmtrans#187]
In steps 9-12 of the windows build there should be an added line for each that also copies the dll with a d at the end of the name, for example it should also copy Qt5Cored.dll with the Qt5Core.dll. Not sure if this is an absolute requirement for all, I would assume so as the exe would not run without these dlls so I'd assume they are needed for the application

Run copy ..\externals\win-deps\qt5-msvc2019-x64\bin\Qt5Core.dll deploy
Run copy ..\externals\win-deps\qt5-msvc2019-x64\bin\Qt5Gui.dll deploy
Run copy ..\externals\win-deps\qt5-msvc2019-x64\bin\Qt5Widgets.dll deploy
Run copy ..\externals\win-deps\qt5-msvc2019-x64\bin\Qt5Svg.dll deploy

**Comment by sykhro** [comment]
The building instructions are meant for "personal uise" and as such they default to release mode. These are debug dlls, useful when in need of debugging without wanting to pull the entire Qt framework
