### ISSUE TITLE
Can't build on x64 Win10.

### ISSUE THREAD

**Issue by vsr3y** [vgmtrans/vgmtrans#188]
I was building the Qt version on x64 Windows 10 until "Run `cmake -GNinja ..`" and it returned
`'cmake' is not recognized as an internal or external command, operable program or batch file.`

I have no prior knowledge on CMake so I installed it and tried to run the command again but this time, it returned

`C:\Users\vsr3y\Documents\Other Applications\build>cmake -GNinja ..`
`CMake Error: The source directory "C:/Users/vsr3y/Documents/Other Applications" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.`

So, I tried moving the build folder into the pulled vgmtrans folder, cd to the build folder inside vgmtrans folder and it returned
 
`CMake Error: CMake was unable to find a build program corresponding to "Ninja".` 
`CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.`
`CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage`
`-- Configuring incomplete, errors occurred!`
`See also "C:/Users/vsr3y/Documents/Other Applications/vgmtrans/build/CMakeFiles/CMakeOutput.log".`

I'm not sure what went wrong, am I supposed to make a file with cmake-gui I just installed first or am I doing something wrong?

**Comment by sykhro** [comment]
> Launch the Visual Studio developer command-line (e.g. x64 Native Tools Command Prompt for VS 2019)
This is crucial. With these errors it seems like you're in a normal command prompt

**Comment by vsr3y** [comment]
> This is crucial. With these errors it seems like you're in a normal command prompt

I tried running `cmake -GNinja ..` again in "Developer Command Prompt for VS 2019" and "Developer Powershell for VS 2019" but it returns the same result as before:

`C:\Users\vsr3y\Documents\Other Applications\build>cmake -GNinja ..`
`CMake Error: The source directory "C:/Users/vsr3y/Documents/Other Applications" does not appear to contain CMakeLists.txt.`
`Specify --help for usage, or press the help button on the CMake GUI.`

**Comment by sykhro** [comment]
you should create the build folder inside the vgmtrans cloned repo and call it from there

**Comment by vsr3y** [comment]
Ok, so I haven't installed Ninja so I've just installed it. Tried deleting vgmtrans folder and tried again from start, created build folder inside cloned repo like you said, but it still shows the same error as the first post.

`C:\Users\vsr3y\Documents\Other Applications\vgmtrans\build>cmake -GNinja ..`
`CMake Error: CMake was unable to find a build program corresponding to "Ninja".    CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.`
`CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage`
`-- Configuring incomplete, errors occurred!`
`See also "C:/Users/vsr3y/Documents/Other Applications/vgmtrans/build/CMakeFiles/CMakeOutput.log".`

**Comment by sykhro** [comment]
When you do this inside the developers' command prompt all the relevant variables should already be set. Check your install with the VS installer

**Comment by vsr3y** [comment]
I downloaded Ninja.exe and put it in CMake folder in Program Files and I'm assuming "Download and install the Build Tools for Visual Studio 2019" only has to do with "MSBuild Tools", not "C++ Build Tools", ".NET desktop build tools" or "Node.js build tools". 

Still got the same error message btw.

**Comment by vsr3y** [comment]
Ok so I've put ninja.exe in a place and set the folder ninja.exe is in to be a PATH variable. Now, I can run `cmake GNinja ..` from build folder but it still fails.

`C:\Users\vsr3y\Documents\Other Applications\vgmtrans\build>cmake -GNinja ..
-- The CXX compiler identification is unknown
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x86/cl.exe - broken
CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/CMakeTestCXXCompiler.cmake:59 (message):
  The C++ compiler

    "C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x86/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/Users/vsr3y/Documents/Other Applications/vgmtrans/build/CMakeFiles/CMakeTmp

    Run Build Command(s):C:/PROGRA~1/Ninja/ninja.exe cmTC_ba6b6 && [1/2] Building CXX object CMakeFiles\cmTC_ba6b6.dir\testCXXCompiler.cxx.obj
    FAILED: CMakeFiles/cmTC_ba6b6.dir/testCXXCompiler.cxx.obj
    C:\PROGRA~2\MIB055~1\2017\BUILDT~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x86\cl.exe    -o CMakeFiles\cmTC_ba6b6.dir\testCXXCompiler.cxx.obj -c testCXXCompiler.cxx
    Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27045 for x86
    Copyright (C) Microsoft Corporation.  All rights reserved.

    cl : Command line warning D9035 : option 'o' has been deprecated and will be removed in a future release
    testCXXCompiler.cxx
    c1xx: fatal error C1356: unable to find mspdbcore.dll
    ninja: build stopped: subcommand failed.





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:11 (project)


-- Configuring incomplete, errors occurred!
See also "C:/Users/vsr3y/Documents/Other Applications/vgmtrans/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/vsr3y/Documents/Other Applications/vgmtrans/build/CMakeFiles/CMakeError.log".`

**Comment by sykhro** [comment]
> "Download and install the Build Tools for Visual Studio 2019"

It means, literally, "Build Tools for Visual Studio 2019", which can be found [here](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16) (comes from [this](https://visualstudio.microsoft.com/downloads/) page, "Tools for Visual Studio 2019" > "Build Tools for Visual Studio 2019"). We don't use MSBuild at all

**Comment by sykhro** [comment]
Once you install that, open the "Developer Command Prompt for Visual Studio 2019 (x64)" and it will work. Then again, why do you want to compile VGMTrans when there's prebuilds?

**Comment by vsr3y** [comment]
Ok, that's the one I used. Download link for "Build Tools for Visual Studio 2019" downloads "vs_BuildTools.exe," which, when opened, presented me with this UI where I can downloads separate build tools packages. The default download option without any packages is "MSBuild Tools" located on the right tab, that's why I assumed it that way. There is no option for "Build Tools for Visual Studio 2019" in the executable itself, only packages. 

Packages (in Workload tab) include:
C++ build tools
Mobile Development with .NET
.NET desktop build tools
Universal Windows Platform build tools
Web Development build tools
Azure development build tools
Office/SharePoint build tools
Data storage and processing build tools
Node.js build tools
.NET Core build tools
Visual Studio extension development

I'm not sure which packages are needed.

![Screenshot 2021-01-16 115941](https://user-images.githubusercontent.com/58370218/104818085-533b5980-57f3-11eb-9c76-dde533df1a6d.jpg)

**Comment by sykhro** [comment]
C++ build tools. Check for stuff like Ninja and Git in the individual components tab

**Comment by vsr3y** [comment]
Also, sorry I wasn't aware of prebuilds. I'd be super if you could link me to one! The prebuild I have working currently is the 2002 one, searching VGMTrans builds led me to this repo's Releases page, which doesn't have any download links besides Interim Build's update log download?
https://github.com/vgmtrans/vgmtrans/releases
Another one is from SMWCentral being 2016 version? Got it working but not sure how updated that is.
https://www.smwcentral.net/?p=section&a=details&id=11655

Also, here's the list of C++ build tools components. If you have prebuilds then I guess we need to pursue it this way anymore!

Thanks for your help!

**Comment by sykhro** [comment]
The latest builds are always available in the actions [tab](https://github.com/vgmtrans/vgmtrans/actions). We should make a new release, it's just that the new version is quite a huge change from the legacy one. Maybe it's time to backport things to master

**Comment by vsr3y** [comment]
Thanks! Finally got it working!
Thanks for your help and patience throughout!

**Comment by sykhro** [comment]
No problem
