### ISSUE TITLE
VgmTrans stops responding when Trying to rip Music from ACWW

### ISSUE THREAD

**Issue by PixL66730** [vgmtrans/vgmtrans#189]
When you put the animal crossing wild world file in VGMTrans
It Loads for about 5 seconds
then stops responding.
Eventually it crashes.

The expected result is the songs get displayed,
but nothing shows and the program stops responding

**Comment by sykhro** [comment]
All the info you're supposed to fill in isn't for decoration, a report like this is useless.

**Comment by PixL66730** [comment]
> All the info you're supposed to fill in isn't for decoration, a report like this is useless.

Sorry was in a hurry

When you put the animal crossing wild world file in VGMTrans
It Loads for about 5 seconds
then stops responding. 
Eventually it crashes.

The expected result is the songs get displayed,
but nothing shows and the program stops responding

**Comment by PixL66730** [comment]
Get the newest release from the actions tab
