### ISSUE TITLE
Program Crashes when trying to Download certain SoundFont (Nintendo DS, Pokemon HeartGold)

### ISSUE THREAD

**Issue by CrazyMew37** [vgmtrans/vgmtrans#192]
So, I was trying to get some soundfonts from the files of a Pokemon Heartgold Rom, but I'm having trouble downloading a certain ROM called 'BANK_GAMEBOY'. Whenever I try to download it as a DLS or SF2, the program immediately crashes. Just Downloading it by itself without conversion doesn't crash it and gives me the file, though I have no clue how to convert that type of file into SF2. (UPDATE Jan. 25, 2021: I should note that trying to play any song that has the file also immediately crashes the program as well.)

In order to reproduce this, it's quite simple:
1. Load a Pokemon HeartGold Rom
2. Find BANK_GAMEBOY in the list of files.
3. Download it as an SF2 or DLS
4. It Crashes VGMTrans

My expected Behavior was to just simply have the SF2 file. I'm collecting some MIDIs and SF2s from Pokemon Games I like so I can listen to them without the use of YouTube.

Here is some info that might help you:
 - OS: Windows 7
 - VGMTrans Version: Unknown, but it says that it was modified on 2/25/2017
 - VGMTrans log: None from what I know.
 - Game ROM or music dump SHA-256: 4787 - Pokemon - HeartGold Version (USA).nds

I'll send the File the Program gave me if that is important by any chance (Converted to .txt so I can send it to here): 
[BANK_GAMEBOY.txt](https://github.com/vgmtrans/vgmtrans/files/5861366/BANK_GAMEBOY.txt)

I hope you are able to see this soon!

**Comment by sykhro** [comment]
See #72

**Comment by CrazyMew37** [comment]
> See #72

So, your telling me that the Gameboy Bank doesn't use audio samples therefore it's sorta impossible to turn into an sf2 with VGMTrans? Is there a way to at least extract and manually convert the file?

**Comment by sykhro** [comment]
Instrument sets can always be exported, provided they have some samples. If it's all pure-synth then you're out of luck. It's a long-standing issue, hopefully we can settle on a fix this year

**Comment by sykhro** [comment]
I'll try to land a fix for the crash asap, so that at least the program doesn't die when browsing collections

**Comment by CrazyMew37** [comment]
Gee, thanks for the info. Good luck on that. I'd love to hear the original Gameboy SoundFont in the future. 🙂
