### ISSUE TITLE
Wrong MIDI dump with Mega Man 8 in Sword Man music (PS1-PSF)

### ISSUE THREAD

**Issue by relu419** [vgmtrans/vgmtrans#194]
I just tested the PSF file and plays perfectly, I saw the information and it's right. Something is wrong with the SEQ-MIDI convertion, just showing a line of "piano" without any note.

**Comment by loveemu** [comment]
As shown in the linked commit, the reported song had an unnatural chunk of zero data, about 8 bytes long, which was incorrectly interpreted as the end of the song, so the SEQ was not parsed to the end. In the latest CI build, the SEQ parser should now work correctly.
