### ISSUE TITLE
NDSSeq: infinite loop in Release mode

### ISSUE THREAD

**Issue by T-wexler** [vgmtrans/vgmtrans#200]
**Describe The Problem**
If SSEQ_0176 - SSEQ_0245 are either played in the app, or are exported as midi, the program freezes then crashes.

**To Reproduce**
Steps to reproduce the problem.
1. Load the game
2. Select any sequence or song between 176 and 245
3. Either play the song through the program, or try to export it

**Expected behavior**
I would expect those files to behave like the rest of the files in the game

**Desktop (please complete the following information):**
 - OS: Windows 10
 - vgmtrans-7d21f50-master-32--Win32-Release
 - No errors or warnings in the log
 - Animal Crossing - Wild World (USA) (Rev 1).nds

**Additional context**
The crash occurs whether you select the sequence on its own, or if you select the package

**Comment by sykhro** [comment]
This seems to be happening only for Release builds, probably due to some optimization

**Comment by T-wexler** [comment]
Sorry I'm late in responding, but is it possible to get/use a non-release build version in Windows?

**Comment by sykhro** [comment]
The only option at the moment would be to compile it yourself

**Comment by sykhro** [comment]
There's definitely something up with optimization at a fundamental level - bug is present across operating systems and compilers. Will push a quick hack soon, hoping it doesn't break anything else.

**Comment by sykhro** [comment]
Using different compilers I was able to trigger this in debug mode with no optimizations. No idea what was happening with MSVC that would make this work in debug mode.

Anyway, the workaround _should_ be fine and it doesn't loop infinitely anymore (will conduct some investigation wrt memory corruption in the near future).
