### ISSUE TITLE
Using keyboard up/down arrows to navigate "file structure" panel doesn't move cursor in hexdump

### ISSUE THREAD

**Issue by nyanpasu64** [vgmtrans/vgmtrans#201]
**Describe the bug**
In the Qt `refactor` branch, on Linux, when I open a sequence in the hex viewer, and use keyboard arrow keys to pick an event in the right panel, the hex viewer's cursor doesn't move.

**To Reproduce**
Steps to reproduce the problem.
1. Open a .spc file (eg. Final Fantasy 6 "Edgar and Sabin").
2. In the left-middle panel, double-click the "music score" item to open the hex viewer.
3. Expand a channel in the right list of channels, then click on an event. The hex editor cursor moves to the event.
4. Use the keyboard arrow keys to switch events in the right list of events. The hex editor's cursor does not move.

**Expected behavior**
The hex editor's cursor moves to the corresponding event.

**Desktop (please complete the following information):**
 - OS: Arch Linux, Qt 5.15.2-5, KDE, Fusion theme
 - VGMTrans version: refactor, 5c7f84ccc728ea91d932072f6bebabbf5eaa9549
 - VGMTrans log: (empty)
 - Game ROM or music dump SHA-256: (Occurs on multiple songs)

**Additional context**
I did not test on Windows.

**Comment by sykhro** [comment]
"Fixed" in `master` with 61835cf3dd9bd88d0ae7a02d44253d3fcd020aff

**Comment by sykhro** [comment]
> Currently is the master or refactor branch more up-to-date?

I'm backporting stuff to master, being less disruptive than in the refactor branch, messing with the core internals in such a radical way wasn't a great idea. Feature parity is near, and I'd like to drop the WTL UI soon (need to figure out packaging for Windows first, which is pretty annoying).

> Also are you aware of any reliable general-purpose techniques for binding user inputs to internal states, then propagating changes in internal state to UI elements, without desyncs like in this bug report if you make a mistake?

I honestly don't know. But another thing for the near future is to move work away from the UI thread, so we'll need to come up with something similar soon I guess

**Comment by nyanpasu64** [comment]
How is packaging broken on Windows? (Looks like AppVeyor does MFC builds, while GHA does Qt builds and calls windeployqt, but it fails on a fluidsynth linking error before reaching packaging.)

Not sure if it's helpful (sorry if I'm rambling too much), but if you want inspiration for Qt packaging, I have a Python packaging script for a Qt application on Windows: https://gitlab.com/exotracker/exotracker-cpp/-/blob/c4393b336f671130d0abd9c77abb3e12eedc337a/ci/build_appveyor.py#L122-160

Another app (I'm not a maintainer) uses appveyor.yml for Windows packaging (though I abandoned this approach due to being too painful to write executable scripts in YAML files): https://github.com/rerrahkr/BambooTracker/blob/2c2d071b2dd0751947ce720713be39bf22e1605e/.appveyor.yml#L117-L142

Both of these call windeployqt.exe, with slightly different flags.

Will Qt be built on AppVeyor, GitHub Actions, or something else? Sadly AppVeyor reduced the binary hosting duration to 1 month, which isn't enough to download historical revisions of active projects, or download the latest version of an inactive project.

Apparently GitHub Actions is designed so you compose build toolchains out of other people's prewritten blocks of code, which the GHA runner downloads from GitHub repositories (like in Docker?), rather than running .yml files or imperative scripts which call systemwide binaries (like in AppVeyor). I have limited experience setting GHA though. One issue is that users who aren't logged into GitHub won't be able to download GHA artifacts. A workaround is to point users to a service like https://nightly.link/, which creates direct links to GHA artifacts.

**Comment by sykhro** [comment]
> How is packaging broken on Windows?

Well, I wouldn't say it's broken, I just need to go through dependency hell and rebuild at least fluidsynth [here](https://github.com/vgmtrans/vgmtrans-ext-win). I might look into using vcpkg on windows if it makes things easier.

> Will Qt be built on AppVeyor, GitHub Actions, or something else?

We already have all the Qt stuff on GHA, Windows included. As for binary storage, we'll figure that out soon (probably pushing to releases in a different repo)
