### ISSUE TITLE
Just does not open.

### ISSUE THREAD

**Issue by JinglBells** [vgmtrans/vgmtrans#208]
when i open the program it says im missing a bunch of DLLs
what gives?

**Comment by sykhro** [comment]
We ask for information for a reason, from your report it's absolutely impossible to determine the problem. What version are you running?

**Comment by JinglBells** [comment]
the latest

**Comment by sykhro** [comment]
> the latest

this is not helpful. I need to know the exact version (I suppose you downloaded it from here) and what dlls are reported as missing. `master` shouldn't depend on any DLLs, so I'm guessing you're using the qt version?

**Comment by JinglBells** [comment]
how can i check the version im not sure what it is, sorry
MSVCP140D.dll
VCRUNTIME140D
VCRUNTIME140_1D
ucrtbased
