### ISSUE TITLE
No playable collections appear on any(SNES/NDS) game

### ISSUE THREAD

**Issue by fiveavril** [vgmtrans/vgmtrans#210]
Every game(have tried a lot, including radiant historia, all SNES FE games, NDS pokemon games, various SNES/NDS jrpgs etc) doesn't pull up any collections when you drag them onto vgmtrans, only sample collection files that do nothing. Example https://imgur.com/a/ES1UTUg Haven't tried any non SNES/NDS games. 

**To Reproduce**
1. Load any snes/nds games(try radiant historia, FE: seisen no keifu, thracia 776, nds pokemon games etc to start) 
2. No collections show

**Expected behavior**
For there to be actual collections that the program can play

**Desktop**
Windows 10
https://github.com/vgmtrans/vgmtrans/releases/tag/interim-20170225
No logs

**Comment by sykhro** [comment]
Huh, this is really weird considering you're using the old build. Are you dropping the files from WinRAR or similar by any chance?

**Comment by fiveavril** [comment]
Nope, I was dragging them directly from my desmume folder for .nds roms for the most part.

**Comment by sykhro** [comment]
Does using the latest build change anything?

**Comment by einso** [comment]
I'm running into the same issues. Not sure about OP, but I am on Windows 11, which could be related.
