### ISSUE TITLE
Compiling C++: Please add /MP flag to enable Multi-processor Compilation for MVSC C++compiler

### ISSUE THREAD

**Issue by tommai78101** [vgmtrans/vgmtrans#213]
**Is your feature request related to a problem? Please describe.**
When building the source code for Windows 10 in the Qt branch, `refactor`, with Visual Studio 2019, there is a lack of parallel build processing. And it takes quite a while to complete building.

What I found out is nearly all of the projects generated by CMake lacks the `/MP` flag. I had to manually add `/MP` to all of the projects in the VGMTrans VS solution. By doing so, it sped up the build, decreasing the build time as a result.

**Describe the solution you'd like**
I would like to request to add `/MP` flags for the Visual Studio 2019 compiler to all projects generated by CMake. 

**Additional context**
OS: Windows 10 x64 20H2 (Non-Insider)
Compiler: Visual C++ (MVSC) 2019

**Comment by sykhro** [comment]
I really didn't want to touch `refactor` much given the `master` effort but I guess this is fine, in the meantime please build with `cmake --build . --parallel` as a workaround.

**Comment by sykhro** [comment]
After having given it some thought, it's better to avoid placing this in CMakeLists - invoke `cmake --build . --parallel` when building

**Comment by tommai78101** [comment]
Understood. We can update this wiki page to reflect upon this.

https://github.com/vgmtrans/vgmtrans/wiki/Building-the-Qt-version

**Comment by sykhro** [comment]
I've updated the page; also pointed it to the `master` branch which is now getting up to speed with the other one.

**Comment by tommai78101** [comment]
Thanks again!
