### ISSUE TITLE
Style not loaded correctly on macOS

### ISSUE THREAD

**Issue by sonictooth** [vgmtrans/vgmtrans#215]
I succesfully compiled vgmtrans on macOS, but when I try to run it, I get a blank window, as shown in the attached screenshot. In the stdout/stderr, I see this error:

QIODevice::read (QFile, ":/qdarkstyle/style.qss"): device not open

<img width="1012" alt="Schermata 2021-05-29 alle 22 45 03" src="https://user-images.githubusercontent.com/1649753/120084330-9c6bb600-c0cf-11eb-8036-3446bb0ee181.png">

**Comment by sykhro** [comment]
This is expected, please build the `refactor` branch. It will be backported to `master` soon

**Comment by sonictooth** [comment]
Oh, I see! Thank you.
