### ISSUE TITLE
Crash when opening any file at all on macOS

### ISSUE THREAD

**Issue by sonictooth** [vgmtrans/vgmtrans#216]
I managed to build the project from source. Whenever I try to open any file of any type, the program always crashes in the exact same way (see the attached crash report).
[crash.txt](https://github.com/vgmtrans/vgmtrans/files/6565316/crash.txt)

**Comment by sykhro** [comment]
Please regenerate cmake files with  `cmake -DCMAKE_BUILD_TYPE=Debug -GNinja ..` and post a log with that version 
(I might not be able to provide a fix for this quickly).

**Comment by sonictooth** [comment]
I rebuilt a debug version but I'm afraid I'm not able to find any log file being generated. The log window in the program remains empty until it crashes. On the standard output, I only see:

`objc[22170]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff945ef3f0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11a0b3f50). One of the two will be used. Which one is undefined.`
`Segmentation fault: 11`

**Comment by sykhro** [comment]
I need the following logs:
- the output of cmake (what gets printed when you invoke `cmake ..` for the first time)
- the crash log from your os (like the one in the first post, when built in debug mode more information should be available)

**Comment by sonictooth** [comment]
Here are the logs.

[cmake.log](https://github.com/vgmtrans/vgmtrans/files/6566847/cmake.log)

[crash2.txt](https://github.com/vgmtrans/vgmtrans/files/6566845/crash2.txt)

**Comment by sykhro** [comment]
The Qt port in `master` is now usable and shouldn't be affected by this issue.
