### ISSUE TITLE
No pitch-bending

### ISSUE THREAD

**Issue by LucianoTheWindowsFan** [vgmtrans/vgmtrans#231]
This was originally posted on vgmtrans-qt, before I realized that one was less up-to-date than vgmtrans itself.
So I loaded music from any compatible SNES game and we didn't have pitch-bending at all.

**To Reproduce**
Steps to reproduce the problem.

1. Check if there's any pitch bending.
2. Load the song
3. Play the song
4. Expected behavior

I expected pitch-bending to happen.

**Desktop:**

OS: Windows 10
VGMTrans continuous-refactor
SHA-256: b65518bf1ea9d83d16b37836580416d6c09b2f757812c1026451538559adbf48
**Additional context**
This song features pitch-bendings even at the start. That song was "Battle Against a Machine" from EarthBound.

**Comment by sykhro** [comment]
We are well-aware #108
