### ISSUE TITLE
Doesn't locate all songs for certain games.

### ISSUE THREAD

**Issue by devonaw** [vgmtrans/vgmtrans#233]
Simple issue, most likely not such a simple fix.
I know of 2 different DS games where the latest version of vgmtrans does not locate all songs:
Rhythm Heaven DS
Mario Vs. Donkey Kong: Mini-Land Mayhem!
I don't even know if this is fixable or if this is already known.

**Comment by sykhro** [comment]
Not all songs are sequenced, VGMTrans isn't made to extract streamed music.
