### ISSUE TITLE
x64 build hard crash when playing song

### ISSUE THREAD

**Issue by PikalaxALT** [vgmtrans/vgmtrans#247]
**Describe the bug**
I compiled the application from HEAD using Visual Studio Community 2019 with the Debug/x64 configuration. When performing the steps below, I receive the following message:

    Unhandled exception at 0x00007FF9D6C54ED9 in VGMTrans_WTL.exe: Microsoft C++ exception: directmidi::CDMusicException at memory location 0x000000CA4953CEA0.

This issue does not occur with the WIn32 configuration.

**To Reproduce**
Steps to reproduce the problem.
1. Build and launch solution with Debug x64 configuration
2. Load the game
3. Scroll to any sseq
4. Press the "Play" button

**Expected behavior**
Audio begins to play

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H1 19043.1165
 - VGMTrans version: 9ce1d07
 - VGMTrans log: (program exits before logs can be exported)
 - Game ROM or music dump SHA-256: `e29bc6ebe431d7a6b238267b6b1521fec4a3bc14f2fa348798062f870c738454`

**Additional context**

**Comment by sykhro** [comment]
Compiling the WTL version as x64 can't work because the API used for playback is 32-bit only. Besides, the WTL version is no longer supported.
