### ISSUE TITLE
Unable to Export .sf2

### ISSUE THREAD

**Issue by Meerkov** [vgmtrans/vgmtrans#256]
I can't get sounds to play within VGMTrans, and can't export soundfont files.

**To Reproduce**

1. Download the latest build for Windows (89b1fae)
2. Drag and drop any game for the PS1 (for example Vagrant Story)
3. Notice that numerous files appear in the left hand panel
4. Double click any file (Akao Sample, Akao Seq, Akao Instr Set, VGMSampColl, Seq, Etc Etc Etc)
5. Click the Green "Play Button" at the bottom of the window.
6. Nothing Happens
7. Try to export any .seq to MIDI (success)
8. Try to export one of the Instr Sets as a .sf2
9. No file is saved at all... nothing happens...

**Expected behavior**
1. I expect the green play button would work.
2. I expect I'd be able to export .sf2 files

**Comment by Meerkov** [comment]
Any chance there is a work around, or some way to figure out what is failing in the extraction? I'd like to export some music, but so far most tools I've found don't succeed in exporting.

**Comment by sykhro** [comment]
No workarounds, sorry. If it's not supported, nothing will magically figure the format out on its own

**Comment by Meerkov** [comment]
No magic is required. A work around could involve a different tool, or perhaps some kind of pointer to where in the code I should be looking to add some error handling.

I wish people wouldn't jump to the assumption that "magic" is the solution I'm looking for. This happens all the time and it's not helpful.

**Comment by sykhro** [comment]
"sf2 doesn't get exported" isn't something that can be worked around. It just means the particular format for the particular game you're trying to convert is either not implemented or bugged. You said "any game for the PS1", which is vague to say the least, since there's many different sequence formats for PS1 games. If you give me a concrete example, I can tell you where the code for that format is.

**Comment by Meerkov** [comment]
For example Vagrant Story.

**Comment by sykhro** [comment]
Vagrant Story is not fully supported. See #98.
