### ISSUE TITLE
SquarePS2 and QSound formats broken

### ISSUE THREAD

**Issue by mikelow** [vgmtrans/vgmtrans#26]
@loveemu,

Oh dear. A git bisect reveals this was caused by the sequence/track loading rewrite in commit b285850.

I first noticed that some notes in QSound have shortened durations. Turns out the problem is with tied note events. You'll find these everywhere in QSound, but for an isolated track, look at sfa2 sequence 10 (Rose) track 6.

Since tied notes in QSound use NoteOn and NoteOff instead of NoteWithDur, I wondered if this problem is affecting other formats that use NoteOn/Off. Sure enough, SquarePS2 uses NoteOn/Off exclusively, and It's totally broken.

Stepping back for a moment, I'm still working on understanding the rewrite code. It seems to have added a lot of complexity and state to the VGMSeq and SeqTrack classes. I understand that some formats require that we process all tracks at once, tick by tick, but I don't think this should be the default approach. This method is more complicated and less intuitive, as it effectively emulates real-time playback. Most formats don't require we do this. My instinct would be to create subclasses of VGMSeq/SeqTrack that handle tick by tick processing for the formats that need it.

Thoughts?

**Comment by loveemu** [comment]
Finally I have checked sfa2 sequence 10. Now it sounds good for me, so I close this issue.
