### ISSUE TITLE
Qt: Assertion errors every time I open or close a file

### ISSUE THREAD

**Issue by loveemu** [vgmtrans/vgmtrans#260]
**Describe the bug**
I get an assertion error when I open or close a file.

![image](https://user-images.githubusercontent.com/3953211/138597875-75fd0dca-6d92-4a18-a0b5-a8237542f955.png)

> Debug Error!
> 
> Program: C:\vgmtrans\build\bin\Qt5Coded.dll
> Module: 5.14.2
> File: C:\Users\Public\Desktop\qsc\qt-everywhere-src-5.14.2\qtbase\src\corelib\itemmodels\qabstractitemmodel.cpp
> Line: 2788
> 
> ASSERT: "last < rowCount(parent)" in file C:\Users\Public\Desktop\qsc\qt-everywhere-src-5.14.2\qtbase\src\corelib\itemmodels\qabstractitemmodel.cpp, line 2788
> 
> (Press Retry to debug the application)

**To Reproduce**
Steps to reproduce the problem.
1. Launching a debug build of VGMTrans
2. Load a file (for example: an SPC file of Chrono Trigger)
3. Debug error!

**Expected behavior**
No assertion errors are displayed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VGMTrans version: master (89b1fae)
 - VGMTrans log: There's nothing special
    ```
    [VGMTransQt] Running interim-20170225 (89b1fae, master), libfluidsynth 2.2.2, Qt 5.14.2
    [VGMFile] Loaded "Presentiment" successfully.
    [VGMFile] Loaded "SNESSampColl" successfully.
    [VGMFile] Loaded "AkaoSnesInstrSet" successfully.
    ```
 - Game ROM or music dump SHA-256: This problem was reproduced with several types of SPC/xSF files.

**Additional context**
I have a feeling that this assertion occurs after the Loader returns DELETE_IT when loading the file, but I am not strongly sure.

**Comment by sykhro** [comment]
This issue has been fixed recently
