### ISSUE TITLE
Inconsistency in bank select strategy between MIDI data and in-app player

### ISSUE THREAD

**Issue by loveemu** [vgmtrans/vgmtrans#264]
## Case 1

**Describe the bug**
In Qt build, some instruments will not be played or will be played as different instruments. This is caused by a bank strategy mismatch between MIDI data and BASSMIDI.

In general, SeqTrack outputs banks in the "mma" style (CC0*128+CC32) as described in Fluidsynth. Therefore, the MIDI data generated by VGMTrans usually selects a bank using CC32. On the other hand, BASSMIDI seems to expect CC0 as a bank select message. (This seemed to be the case even when XG Reset sysex was sent.)

This did not happen in the WTL version. This is probably because DirectMusic uses DLS, and DLS should be able to set the bank number in MSB/LSB.

**To Reproduce**
Steps to reproduce the problem.
1. Load SNES Donkey Kong Country 2: Klubba's Reveille (dkq-23.spc)
2. The low brass sound is played by a square-like synth (some other instruments also have problems)

Later AKAOs (e.g. Final Fantasy IX) are also good for checking the performance of banked instruments.

## Case 2

The following problem used to occur with Fluidsynth, but no longer occurs after switching to BASSMIDI. Just be careful not to let it happen again in the process of fixing the problem above.

**Describe the bug**
The drum sounds of late SNES AKAO songs don't sound right, but are instead played by a saw-like synth or something.

In this case, the bank number of the drum is defined as `(127 << 14)`, so VGMTrans will output bank MSB=127 to the MIDI data.

**To Reproduce**
Steps to reproduce the problem.
1. Load the Battle theme from Chrono Trigger (ct-112.spc), for example
    * In addition to Chrono Trigger, the same problem can be seen in Romancing SaGa 3 and Gun Hazard
2. The drum sounds such as snares are played by a saw-like synth

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VGMTrans version: e579b9c, master
 - VGMTrans log: No errors or warnings
 - Game ROM or music dump SHA-256: [Super Donkey Kong 2: Dixie & Diddy ~ SNESmusic.org](http://snesmusic.org/v2/profile.php?profile=set&selected=15924)
 - Game ROM or music dump SHA-256: [Chrono Trigger ~ SNESmusic.org](http://snesmusic.org/v2/profile.php?selected=554&profile=set)

**Comment by loveemu** [comment]
The same goes for Donkey Kong Country 2: Diddy's Kong Quest, etc.?　I haven't checked in detail, but I'm guessing this may be a bank select issue between DirectMusic and FluidSynth.

**Comment by sykhro** [comment]
Will check this out soon. This is unfortunately the price to pay when switching between DLS and SF2, I suspect they are not equal. Unfortunately, fluidsynth DLS playback is problematic to enable since it has way too many dependencies

**Comment by loveemu** [comment]
The drum instrument is selected with bank MSB=127, LSB=0. There is no concept of MSB/LSB in SoundFont banks, so I assume this is the reason why fluidsynth's bank selection is not working as expected and different instruments are being selected. If fluidsynth had a way to determine whether the bank number should be selected from MSB or LSB, this could be avoided.

**Comment by sykhro** [comment]
> The drum instrument is selected with bank MSB=127, LSB=0. There is no concept of MSB/LSB in SoundFont banks, so I assume this is the reason why fluidsynth's bank selection is not working as expected and different instruments are being selected. If fluidsynth had a way to determine whether the bank number should be selected from MSB or LSB, this could be avoided.

FluidSynth supports this as an option, my setting `synth.midi-bank-select` to "xg".
https://www.fluidsynth.org/api/fluidsettings.xml#synth.midi-bank-select

**Comment by loveemu** [comment]
There is still a problem with bank strategies in BASSMIDI, so I am reopening the issue. Fortunately, I feel that this is not that difficult to fix. I think this problem can be solved by having the MIDI file (SeqTrack) and DLS follow a "gs" style (CC0 preferred) bank numbering strategy.

**Comment by sykhro** [comment]
> There is still a problem with bank strategies in BASSMIDI

Do you have an example? Right now we're telling BASSMIDI to load all presets to bank 0:
https://github.com/vgmtrans/vgmtrans/blob/master/src/ui/qt/SequencePlayer.cpp#L205-L208
If we need to use bank 1 or other banks, we should be able to configure it from there. However, migrating to GS would be beneficial for other players

**Comment by sykhro** [comment]
Should be fixed in #298. With GS mode I no longer hear the square synth in the DKC song you mentioned
