### ISSUE TITLE
Loop event inside Midi.

### ISSUE THREAD

**Issue by RetroGamesClub** [vgmtrans/vgmtrans#265]
Is it possible to create Midi Loop Start/End event inside Midi files created from DS OST? Thank you.

**Comment by Wohlstand** [comment]
I'll append, there are some formats for loop points that were supported by various players:
- markers that contain "loopStart" and "loopEnd" keywords came from the music for Final Fantasy VI and were supported by many players and by Sekaiju (for example, my MIDI sequencer used at libADLMIDI and libOPNMIDI supports this loop format natively)
- Using CC111 controller came from the RPG Maker

There is also other loop tags format, but they are very uncommon and I don't suggest supporting them. FFVI and RPG Maker loop formats were most common.
