### ISSUE TITLE
'fluidsynth.h': No such file or directory

### ISSUE THREAD

**Issue by LucianoTheWindowsFan** [vgmtrans/vgmtrans#266]
So I was compiling the original vgmtrans. There is a build issue tag on here, but that is only for the QT version, and I'm compiling the WTL version.

I got an error about fluidsynth.h. I got it on the same directory as the file it looks for.

I'm working on support for Sunsoft's variant of the N-SPC.

**Comment by sykhro** [comment]
WTL doesn't use fluidsynth, it shouldn't even be looking for that file. How are you building it?
