### ISSUE TITLE
Improve startup time by optimizing DirectMusic port enumeration in CMidiPort class

### ISSUE THREAD

**Issue by ValleyBell** [vgmtrans/vgmtrans#28]
Depending on the installed MIDI drivers on a computer, vgmtrans can take a long time to boot.
My computer lists 8 DirecMusic devices (including BASSMIDI and VST MIDI drivers) and it takes about 30 seconds to boot.

The source of the issue seems to be the way devices are enumerated in the CMidiPort class.
On my system m_pMusic8->EnumPort() takes 3 seconds to get the information of device 0 (MIDI mapper), all other devices are enumerated fairly quickly.

Unfortunately EnumPort() is called not only to get the number of available devices (GetNumPorts), but it also is called N times when getting the device information for the Nth port in GetPortInfo. (It enumerates from 0 onwards until the Nth valid device is reached.)
So in my case it calls EnumPort() for device 0 nine times in total, each time taking 3 seconds.

If the CMidiPort class would get the information of all devices once during the initialization phase and cache them for GetPortInfo, it would reduce the boot time a lot.

**Comment by loveemu** [comment]
Your report is informative and it helped me a lot. Thank you very much.
