### ISSUE TITLE
Windows: Having "Save All" Commands

### ISSUE THREAD

**Issue by loveemu** [vgmtrans/vgmtrans#3]
Having something like "Save All Selected Sequences As MIDI" seems to be useful to convert all songs of the game. I'd like to use it.

Multiple files can be selected in Collections tab and it provides Save menu, but it saves only a single file.

**Comment by SamusAranX** [comment]
Um... not trying to be pushy or anything, but this issue is two years old now and nothing has happened.
Will this eventually be implemented or is this issue just here for the sake of posterity?

**Comment by sykhro** [comment]
Implemented in the `refactor` branch. Closing this as WTL is essentially unmantained
