### ISSUE TITLE
Where can I download an executable binary?

### ISSUE THREAD

**Issue by Gamerguy100** [vgmtrans/vgmtrans#30]
WHERE IS THE APPLICATION? THRE ISNT AN EXE FILE? I SPELLED THE 5TH WORD WRONG.

**Comment by DaveyJones21** [comment]
None of the releases contain an executable binary. If they are there, how do I access them? I am unable to compile it by myself simply because I do not know how.

**Comment by sykhro** [comment]
They are always available in appveyor
https://ci.appveyor.com/project/loveemu/vgmtrans/builds/24670095/artifacts

**Comment by DaveyJones21** [comment]
Thank you, I'm just an idiot and forgot I could extract .7z files
