### ISSUE TITLE
CPU/General usability issue on the latest Mac OS port build.

### ISSUE THREAD

**Issue by Legosi13** [vgmtrans/vgmtrans#302]
I am currently using a 16GB, 3Ghz iMac running the latest version (as of March 31st), _OS X Monterey 12.3_ and with all due respect: why does a singular [mini2sf] music file devour my CPU bandwidth when it's not even loading at all (I've given it some time, even closed down other items to see if it'd make a difference). Activity Monitor (which I'll provide a screenshot of) reads that vgmtrans is on an average bandwidth range of 94% to even numbers as outrageous as 102%. Despite said readings, it does not appear this Mac OS build functions beyond basic interactions with the GUI-- it simply refuses to open any supported format without hanging indefinitely.

Thanks,
Mokusei 
<img width="834" alt="Screen Shot 0004-03-31 at 22 36 48" src="https://user-images.githubusercontent.com/67709387/161185035-6655510c-23d1-4a01-b35e-bd9aaceac18b.png">

**Comment by sykhro** [comment]
With all due respect, had you filled out the template I'd at least know what version of VGMTrans you're running.
In general, sometimes VGMTrans can end up in an infinite loop, especially if the mini2sf dump is bad.  Nobody will be able to help you unless you fill the issue template as-is

**Comment by Legosi13** [comment]
I'm using the latest build. "VGMTrans-28601b54ed1c38471f67a6ff4ff4c5d32d7291fd-master-x86_64-macOS"

**Comment by sykhro** [comment]
What games/formats have you tried to use?

**Comment by Legosi13** [comment]
Primarily the minisf2 format, more so from "WarioWare: Touched!" sourced directly from Zorphar's Domain. Previously if I recall correctly I used Kirby Super Star Ultra from the same source, and with the more later builds they seemed to work fine. I may have to test the latest build to see if it works just as well as the last time I recall importing KSSU songs.

**Comment by mikelow** [comment]
> sometimes VGMTrans can end up in an infinite loop, especially if the mini2sf dump is bad

^
