### ISSUE TITLE
.nspc support

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [vgmtrans/vgmtrans#309]
**Is your feature request related to a problem? Please describe.**
.nspc refers to the music data stored in the ROM. .spc is a capture of the ARAM.
**Describe the solution you'd like**
Make vgmtrans support .nspc files (nintendo snes sound engine)

**Comment by Bonboon229** [comment]
.nspc is not a music file extension.

**Comment by H-A-M-G-E-R** [comment]
WRONG
PROOF: https://github.com/tewtal/mITroid

**Comment by sykhro** [comment]
N-SPC is one of the most common engines and we already support it. We might not be supporting the specific variant for the game you need. Please provide more specific information
