### ISSUE TITLE
Problem with sound!

### ISSUE THREAD

**Issue by netocodec** [vgmtrans/vgmtrans#315]
### Environment details

* Operating System+version: Windows 10
* VGMTrans version: (381fd0a, master)

### Describe the bug

I compiled the latest version of VGMTrans, it compile well without problems, i click on the binary to run it, i can load the .minipsf file, but the problem is i don't have a "Collection" of the music, i tried to add manually, it creates well the collection but when i want to convert it into MIDI file or play it on the application it gives me nothing, including the MIDI file.

Can you help me? I tried even on a Linux Ubuntu machine and it gives me the same result.

![imagem](https://user-images.githubusercontent.com/71384123/181497762-01d97f26-56ed-4095-913f-9b5125426604.png)

There is the files that i want to open: https://we.tl/t-fo9ZI1rs0K

### Expected behaviour

I was expecting to get automatically the collections of the music and then play it

**Comment by mikelow** [comment]
Can't access the uploaded file any more. Sorry there wasn't a more timely response. Probably an issue with "optimized" PSFs that removed unread bytes, which unfortunately include those that associate the sequence with the instr data set. Haven't looked into manual collection creation in this case, but it may not work when a format requires multiple sample collections.
