### ISSUE TITLE
Segmentation fault when closing application with collections open

### ISSUE THREAD

**Issue by KungFuFurby** [vgmtrans/vgmtrans#329]
### Environment details

* Operating System+version: macOS Catalina 10.15.7
* VGMTrans version: 1.1
* Game ROM/music dump name and sha256: N/A

### Describe the bug

I get a segmentation fault when closing the application while a collection is open.

<img width="501" alt="VGMTrans Quit Unexpectedly Screen Shot" src="https://user-images.githubusercontent.com/7094832/198177599-aca530a5-bdba-40c9-9482-17c72ed4c434.png">

### Steps to reproduce

1. Load any music file, or collection.
2. Close the program or the window (which also closes the program) while the collection is still open. Deleting it from the collections section will cause this to not happen.
3. You will be notified that VGMTrans quit unexpectedly.

### Expected behaviour

The program should close without giving me a notification that it quit unexpectedly.

### Logs

[Here's the crash log as a .txt file.](https://github.com/vgmtrans/vgmtrans/files/9875281/VGMTrans.Crash.Log.txt)
(the crash log was too big for me to just post here, even in a spoiler)

**Comment by mikelow** [comment]
Fixed by #409
