### ISSUE TITLE
Improve slider event support

### ISSUE THREAD

**Issue by loveemu** [vgmtrans/vgmtrans#35]
- Cancellable slider (Example: Yoshi's Island - Lesson Level)
- Non-linear slider (exponential etc.)
- Pitch slider (note we need to remember pitch bend range)
- Tempo slider

I think I will make an Interpolation class someday.

**Comment by jimbo1qaz** [comment]
**akaospc**: Can you pass through (pan) slide events as text events for manual parsing? Right now they are silently discarded, preventing me from writing a manual conversion tool.

Also, I may decide to add pitch/pan slider conversion support to my MIDI tool, by converting bends into tick-quantized control change events. What tick spacing should I use between adjacent events?

**Comment by loveemu** [comment]
This issue is too generic and too old. I think we can think about this problem deeper in discussion or project if needed.
