### ISSUE TITLE
vgmtrans refuses to launch on linux

### ISSUE THREAD

**Issue by albert-softie** [vgmtrans/vgmtrans#352]
### Environment details

* Operating System+version: EndeavourOS Linux x86_64, kernel 6.1.20-1-lts
* VGMTrans version: Build # 310: Commit [89fb5e3](https://github.com/vgmtrans/vgmtrans/commit/89fb5e386285c2a3ae139475795217558e2e4c2d) pushed by [sykhro](https://github.com/sykhro)

### Describe the bug

the application fails to launch, citing a missing qt platform plugin as the problem

### Steps to reproduce

1. Load the appimage

### Expected behaviour

the program launches

### Additional context

after some testing, it seems like this was a bug introduced in commit [be66b5c](https://github.com/vgmtrans/vgmtrans/commit/be66b5c3392157b02951494f78eedeec7f299463), as the build from the commit before it does not fail to launch

### Logs

<details><summary>Click to expand log</summary>

```
[albert-softie@albert-softie-endeavouros Applications]$ ./VGMTrans.AppImage
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
[albert-softie@albert-softie-endeavouros Applications]$ 

```

</details>

**Comment by sykhro** [comment]
`linuxdeployqt` being annoying around Wayland as usual. I have reverted CI to use Qt5, next build should be working again

**Comment by sykhro** [comment]
This has been fixed. Please reopen if you still encounter issues.
