### ISSUE TITLE
Refactoring data interfaces

### ISSUE THREAD

**Issue by sykhro** [vgmtrans/vgmtrans#357]
**Is your feature request related to a problem? Please describe.**
The current `RawFile` API is very painful to work with. It has some hidden state (`DataSeg`), it relies on copying buffers around, can't be used with STL algorithms and it's generally very inefficient.

**Describe the solution you'd like**
Rework the `RawFile` API so that:
- it works with `span`
- can support memory-mapped files
- has `const`-correctness
- can support STL algorithms
- can co-exist with the old API

**Additional context**
This was already attempted in `refactor` so it can be used as reference. However, we should be leveraging c++20 this time.

**Comment by mikelow** [comment]
Yeah. It sucks. There are a lot of things under the hood that could use a total rewrite.

**Comment by sykhro** [comment]
The idea here is to introduce a new API that can co-exist with the current. Otherwise we'd have to mass-rewrite everything, which has proven to be bug-prone. And unrealistic, since so far this project has been thriving on bursts of free time :p

**Comment by mikelow** [comment]
@sykhro, I was looking into adding background threaded loading, and realized that RawFile, particularly its use of the awful DataSeg implementation, is a liability for multithreaded file access. I looked into your `refactor` branch implementation and the changes you made there more broadly. It looks like you have a lot of good work in there that never made it into the master branch. So I have some questions, both about your RawFile implementation, and about the refactor branch in general.

First, with RawFile, you mentioned you'd like to leverage C++20. What features of C++20 do you have in mind, and is there anything specific you would change about your version in refactor? Is there a reason not to take your current work, merge it in, and iterate on it?

Second, I'd like to get more information about the `refactor` branch. Where do things stand with it? Were there any issues or unfinished business that held you back from merging it into master? It's unfortunately difficult for me to distinguish which commits are unique from the master branch since the commit messages seem different. Do you have any thoughts on how we might best merge the hard work you did?

**Comment by sykhro** [comment]
> First, with RawFile, you mentioned you'd like to leverage C++20. What features of C++20 do you have in mind, and is there anything specific you would change about your version in refactor?

c++20 has a whole new standard library inside of `std::ranges`, I wanted to see if there's anything in there that can make our implementations simpler. Honestly c++17 is probably enough and converting things that need to access the file bytes to use `std::span` would work.

> Is there a reason not to take your current work, merge it in, and iterate on it?

A possible reason is that it's been a while so I don't remember what I broke in the process of changing that code :D 

> Second, I'd like to get more information about the refactor branch. Where do things stand with it? Were there any issues or unfinished business that held you back from merging it into master? It's unfortunately difficult for me to distinguish which commits are unique from the master branch since the commit messages seem different. Do you have any thoughts on how we might best merge the hard work you did?

I had your same goal in mind. I started the refactor branch with the intention of:
- fully decoupling ui from the conversion logic
- making things thread-safe
- reimplementing parts of the api to make it "unsurprising" to c++ devs
- switching to post-c++11 idioms (values are cool now)

As time went on I realized I had what I call Netscape syndrome: I was reimplementing stuff just "to make it nicer" while doing 0 progress on bugfixes and features. So then I started again on master, limiting the scope to more achievable goals without having to rewrite everything. Some commits are cherry-picked from refactor, some are new.

**Comment by mikelow** [comment]
I think the work you did in the `refactor` branch is important and it's worth working through it. I've created a new `refactor-redux` branch where I'm taking a stab at merging much of it into `master`. I assume you don't mind my taking this upon myself - I want you to be credited in git, so I'll look options for that. I started by just pulling in your changes to `RawFile`, but there are so many interdependent changes that this will be a big PR, assuming I finish it. Obviously, I'd rather break this into smaller changes, but that would be major task unto itself 🤷‍♂️.

> c++20 has a whole new standard library inside of std::ranges, I wanted to see if there's anything in there that can make our implementations simpler. Honestly c++17 is probably enough and converting things that need to access the file bytes to use std::span would work.

Thanks for explaining, this is helpful. For now I'm going to stick with your implementation as-is, in RawFile and elsewhere. Hopefully this will make evaluating the PR easier.

> A possible reason is that it's been a while so I don't remember what I broke in the process of changing that code :D

I think I have to just suffer through a lot of testing. It's either that or be paralyzed to improve the codebase out of fear of breaking things.

> I had your same goal in mind. I started the refactor branch with the intention of:
> - fully decoupling ui from the conversion logic
> - making things thread-safe
> - reimplementing parts of the api to make it "unsurprising" to c++ devs
> - switching to post-c++11 idioms (values are cool now)

💯

> As time went on I realized I had what I call Netscape syndrome: I was reimplementing stuff just "to make it nicer" while doing 0 progress on bugfixes and features. So then I started again on master, limiting the scope to more achievable goals without having to rewrite everything. Some commits are cherry-picked from refactor, some are new.

I get the frustration, though, again, I think your refactoring work is extremely valuable and given how flawed the original code is, absolutely worth the effort.

 Do you know if the `refactor` branch was left in a compilable state? I'd test it myself but I'd have to install qt5 or fish for and cherry pick the qt6 changes.

**Comment by sykhro** [comment]
It won’t work with Qt6 as it didn’t exist at the time.As for commit authorship, you can add me using Co-authored-by in the commit message.One thing i wouldn’t pull from that branch is the logging stuff, Let’s use spdlog instead On 27 Apr 2024, at 02:44, Mike ***@***.***> wrote:﻿
I think the work you did in the refactor branch is important and it's worth working through it. I've created a new refactor-redux branch where I'm taking a stab at merging much of it into master. I assume you don't mind my taking this upon myself - I want you to be credited in git, so I'll look options for that. I started by just pulling in your changes to RawFile, but there are so many interdependent changes that this will be a big PR, assuming I finish it. Obviously, I'd rather break this into smaller changes, but that would be major task unto itself 🤷‍♂️.

c++20 has a whole new standard library inside of std::ranges, I wanted to see if there's anything in there that can make our implementations simpler. Honestly c++17 is probably enough and converting things that need to access the file bytes to use std::span would work.

Thanks for explaining, this is helpful. For now I'm going to stick with your implementation as-is, in RawFile and elsewhere. Hopefully this will make evaluating the PR easier.

A possible reason is that it's been a while so I don't remember what I broke in the process of changing that code :D

I think I have to just suffer through a lot of testing. It's either that or be paralyzed to improve the codebase out of fear of breaking things.

I had your same goal in mind. I started the refactor branch with the intention of:

fully decoupling ui from the conversion logic
making things thread-safe
reimplementing parts of the api to make it "unsurprising" to c++ devs
switching to post-c++11 idioms (values are cool now)


💯

As time went on I realized I had what I call Netscape syndrome: I was reimplementing stuff just "to make it nicer" while doing 0 progress on bugfixes and features. So then I started again on master, limiting the scope to more achievable goals without having to rewrite everything. Some commits are cherry-picked from refactor, some are new.

I get the frustration, though, again, I think your refactoring work is extremely valuable and given how flawed the original code is, absolutely worth the effort.
Do you know if the refactor branch was left in a compilable state? I'd test it myself but I'd have to install qt5 or fish for and cherry pick the qt6 changes.

**Comment by mikelow** [comment]
@sykhro I'm of a mind to somewhat aggressively mark this issue and the [reimplement logging](https://github.com/vgmtrans/vgmtrans/projects/4#card-65180831) card Done, unless you object. I know we may not have achieved your goal of standard library integration, but perhaps for a sense of progress, we should scope this down. We can always make a new ticket and/or project if we please.

**Comment by sykhro** [comment]
> @sykhro I'm of a mind to somewhat aggressively mark this issue and the [reimplement logging](https://github.com/vgmtrans/vgmtrans/projects/4#card-65180831) card Done, unless you object. I know we may not have achieved your goal of standard library integration, but perhaps for a sense of progress, we should scope this down. We can always make a new ticket and/or project if we please.

Yeah, I would say this can be considered done
