### ISSUE TITLE
Should be able to extract .3ds files

### ISSUE THREAD

**Issue by ThatDomino** [vgmtrans/vgmtrans#361]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**
If you are asking for a new format to be supported, please provide some details about it

**Comment by overcast07** [comment]
Most 3DS games don't have any sequenced music that VGMTrans could export. For the few that do have some, you could try using [caesar](https://github.com/kr3nshaw/caesar).
