### ISSUE TITLE
Show error messages when crashing

### ISSUE THREAD

**Issue by overcast07** [vgmtrans/vgmtrans#384]
**Is your feature request related to a problem? Please describe.**
VGMTrans typically crashes immediately when importing an unreadable file, and may crash in other situations. The user isn't given any information about why the program might have crashed.

**Describe the solution you'd like**
Ideally, VGMTrans should avoid crashing, or inform the user of the problem that caused the crash by displaying an error message. I don't know if this is possible.

**Comment by sykhro** [comment]
To be able to do this we would need a separate thread or process to handle the whole scanning and conversion process. I agree that the program shouldn't crash, but it's not something that can be fixed without a moderately sized refactor
