### ISSUE TITLE
Support for My Little Pony: Pinkie Pie's Party (NDS) sound format

### ISSUE THREAD

**Issue by overcast07** [vgmtrans/vgmtrans#386]
**Is your feature request related to a problem? Please describe.**
_My Little Pony: Pinkie Pie's Party_ (NDS) appears to be a game that uses an unsupported sequence format, since the audio channels can be muted in DeSmuME.

I understand that it is unlikely for support for these kinds of obscure formats to be implemented in the near future, but I am making a note of it here for completeness, in case it could happen at some point.

**Describe the solution you'd like**
When importing the ROM of the game into VGMTrans, the sequences and soundbanks of the game should ideally be playable and exportable in VGMTrans.

**Additional context**
This game was developed by THQ, but other THQ NDS games use the normal NDS sound driver. I don't know why this one specifically uses something else.

**Comment by mikelow** [comment]
Requests for new format support don't belong in Issues.
