### ISSUE TITLE
Download links are fake

### ISSUE THREAD

**Issue by Moltresrider** [vgmtrans/vgmtrans#390]
### Environment details

Does not apply, trying to get the program.

### Describe the bug

It is literally impossible to download the program because every link claiming to have a build on this Github is fake or not clickable. 

### Steps to reproduce

Visit this github
Click every link related to "Windows" and "build"

### Expected behaviour

There should be a download link, not links to fake files that are not clickable and difficult to find. 

### Logs

<details><summary>Click to expand log</summary>

```
REPLACE THIS LINE WITH YOUR LOG
```

</details>

**Comment by sykhro** [comment]
> every link claiming to have a build on this Github is fake or not clickable.

[Looks clickable to me](https://github.com/vgmtrans/vgmtrans/actions/workflows/build.yml).
[Latest build doesn't seem fake either](https://github.com/vgmtrans/vgmtrans/actions/runs/5871674163).
[The homepage also has some links](https://vgmtrans.github.io/vgmtrans/),
which lead to [more clickable links with the latest build!](https://nightly.link/vgmtrans/vgmtrans/workflows/build/master).

We are aware that the GitHub UX for downloading builds isn't great. However, we have answered this question a million times and the builds are there.
