### ISSUE TITLE
Animal Crossing: Wild World Infinite Loop - curOffset repeats values in NDSSeq.cpp on line 137

### ISSUE THREAD

**Issue by tommai78101** [vgmtrans/vgmtrans#45]
There is an infinite loop that occurs when extracting SDAT from the NDS game, Animal Crossing: Wild World.

The current offset (curOffset) on line 137 is always updated, but it never exceeds stopOffset. It keeps repeats the following values: 0x01397829, 0x0139782b, 0x0139782d, and 0x0139782f.

**Comment by sykhro** [comment]
Should be fixed by https://github.com/vgmtrans/vgmtrans/commit/fde6f97a160bd49465ae87cd1e92f325f0e1c896

**Comment by tommai78101** [comment]
OHHHH, many thanks for this!

**Comment by sykhro** [comment]
Please let me know if this can be closed

**Comment by tommai78101** [comment]
@sykhro  Yep, seems to be working. I can now play audio from inside vgmtrans, which is good enough in my opinion. I'll close this issue for you.
