### ISSUE TITLE
SHORT DESCRIPTION

### ISSUE THREAD

**Issue by RetroGamesClub** [vgmtrans/vgmtrans#452]
### Environment details

Windows 10, latest release just downloaded.

### Describe the bug

Mulitple selection, to allow multiple export of .mid and .sf2 (from a Nitendo DS game), is no more working. (in previous release, last time i downloaded in February, multiple selection and export was working fine).
  

### Steps to reproduce

Any NDS tom

### Expected behaviour

Multiple selection and export. 

### Logs

<details><summary>Click to expand log</summary>

```
REPLACE THIS LINE WITH YOUR LOG
```

</details>

**Comment by mikelow** [comment]
Fixed
