### ISSUE TITLE
Capcom Q Sound "Unknown" Instrument Parameter (Fine-Tuning)

### ISSUE THREAD

**Issue by felinek** [vgmtrans/vgmtrans#50]
Hi, was just shown this program by a friend the other day, and as someone who has long been interested in Capcom's QSound soundtracks, I love it! However, I would like to point out one issue in your implementation of the QSound format. One parameter in the instrument definitions is currently listed as "Unknown". Based on my prior research, it would seem this is a signed fine-tuning value. Listening to Super Street Fighter 2 Turbo's soundtrack as played back in the program, the electric piano instrument (instrument 0143) is noticeably out of tune (listen to arpeggio a few seconds into song 3 for a good example) , and I believe it might be due to the lack of this parameter being reflected.

**Comment by mikelow** [comment]
You are indeed, correct, and yes that fixes the issue.
