### ISSUE TITLE
`6f6f86823ab10ce72f0c6acd6ef7991e631613f7` segfaults start on Windows 10

### ISSUE THREAD

**Issue by RetroGamesClub** [vgmtrans/vgmtrans#518]
Previous release (latest I've installed war 15 april was working fine).
Aldo

**Comment by sykhro** [comment]
What error do you get?

**Comment by RetroGamesClub** [comment]
I get no error. Simply app won't start. 

Non parte proprio. Non riesco a vederlo neanche in gestione attività

**Comment by sykhro** [comment]
Apri un terminale, trascina l'exe dentro al terminale, premi invio. Esce niente?

**Comment by RetroGamesClub** [comment]
No, va a capo e torna sul prompt dei comandi.

**Comment by RetroGamesClub** [comment]
Ho controllato sul visualizzatore eventi di windows:

Nome dell'applicazione che ha generato l'errore: vgmtrans.exe, versione: 0.0.0.0, timestamp: 0x666f49e2
Nome del modulo che ha generato l'errore: MSVCP140.dll, versione: 14.29.30135.0, timestamp: 0x612d915a
Codice eccezione: 0xc0000005
Offset errore 0x0000000000013020
ID processo che ha generato l'errore: 0xc0c
Ora di avvio dell'applicazione che ha generato l'errore: 0x01dac23f6b04c850
Percorso dell'applicazione che ha generato l'errore: F:\utility\vgmtransqt\bin\vgmtrans.exe
Percorso del modulo che ha generato l'errore: C:\WINDOWS\SYSTEM32\MSVCP140.dll
ID segnalazione: a70e2f22-0506-4710-bb36-e221039ba60b
Nome completo pacchetto che ha generato l'errore: 
ID applicazione relativo al pacchetto che ha generato l'errore:

**Comment by sykhro** [comment]
Quale commit hai usato?

**Comment by Excalibur624** [comment]
I had this exact same issue with the exact same message. What fixed it was to reinstall the Virtual C++ redistributable, now vgmtrans will open

**Comment by RetroGamesClub** [comment]
Which redistributable release?

**Comment by RetroGamesClub** [comment]
Thank you. This solved for me too.

**Comment by mikelow** [comment]
Great! Closing this.
