### ISSUE TITLE
Cannot build with VS2015 Community

### ISSUE THREAD

**Issue by StarWolf3000** [vgmtrans/vgmtrans#52]
Trying to build with Visual Studio 2015 Community (successor of Visual Studio Express) results in linking errors against DxErr.lib and tinyxmlSTL-mt.lib.

packaged tinyxml:
LNK2038 - _MSC_VER mismatch between 1800 and 1900
LNK2001 - several unresolved external symbols

Solution:
Rebuild tinyxml with your own compiler

packaged DxErr.lib:
LNK2001 - unresolved external symbols _vsnprintf and _vsnwprintf

Solution:
Use [FormatMessage function (Windows)](https://msdn.microsoft.com/en-us/library/windows/desktop/ms679351.aspx) instead of the DX*
See [Where's DXERR.LIB?](http://blogs.msdn.com/b/chuckw/archive/2012/04/24/where-s-dxerr-lib.aspx)

**Comment by loveemu** [comment]
Updated resources for VS2015. Thank you very much for the info!

**Comment by StarWolf3000** [comment]
This works now, but occasionally brings new problems:

Upon clicking "Play" (after loading a ROM/Sound Dump, regardless of the type), it crashes and closes. In the Debugger it stops at the routine where it loads the Soundbank from Memory.

When I'm at home tomorrow, I will post the debuggers output (which will be in german, because of my locale).

**Comment by loveemu** [comment]
It's working fine for me. Does your problem occur with the precompiled binary of [latest release](https://github.com/vgmtrans/vgmtrans/releases/tag/interim-20151003)?

**Comment by StarWolf3000** [comment]
Nope. If I run your latest precompiled, the audio plays fine and is not crashing.

**Comment by StarWolf3000** [comment]
It seems that it will always crash if I build a 64-bit version and run this. Building a 32-bit/x86 version works without problems.

**Comment by loveemu** [comment]
Yeah, 64bit version does not work, at least it will cause a problem with DirectMusic.

I will check if there are another problems when I have enough time, but it won't be worked after all. Thanks.
