### ISSUE TITLE
[SPC SUPPORT] Power Slide Demo Theme won't open

### ISSUE THREAD

**Issue by SecularSteve** [vgmtrans/vgmtrans#534]
### Environment details

* Operating System+version: Windows 10 20H2
* VGMTrans version: [VGMTrans-456fd6f14f3c3ea7f71f366500cfbd36950f8f5c-master-x64-Windows](https://nightly.link/vgmtrans/vgmtrans/workflows/build/master/VGMTrans-456fd6f14f3c3ea7f71f366500cfbd36950f8f5c-master-x64-Windows)
* Game ROM/music dump name and sha256: Power Slide ECTS Demo (01 Main Theme.spc), SHA-256: 83e31308b6d41351c8c4e708df618eda75f87729fed93daecbeebad30054527f (File comes from Zophar's SPC rip of the game)

### Describe the bug

Something about an unknown id tag with one of the instruments.

I'm not into the technical know-how here. I just wanted to convert it to MIDI.

### Steps to reproduce

1. Load VGMTrans
2. Try to open the SPC

### Expected behaviour

n/a

### Additional context

[Power Slide ECTS Demo (MP3).zophar.zip](https://github.com/user-attachments/files/16521957/Power.Slide.ECTS.Demo.MP3.zophar.zip)
[Power Slide ECTS Demo (EMU).zophar.zip](https://github.com/user-attachments/files/16521958/Power.Slide.ECTS.Demo.EMU.zophar.zip)

https://fi.zophar.net/soundfiles/nintendo-snes-spc/power-slide-ects-demo/01%20Main%20Theme.mp3

### Logs

<details><summary>Click to expand log</summary>

```
Running (456fd6f, master), BASS 2041100, Qt 6.6.1
Unknown id6 tag id: 19 in SPC
Unknown id6 tag id: 19 in SPC
```

</details>

**Comment by KungFuFurby** [comment]
I'll actually jump in despite the closure, realizing what you're trying to do... You're also dealing with an unimplemented sound driver, courtesy of Motivetime/Richard Frankish, so the music format is not supported either.
