### ISSUE TITLE
Syphon Filter (PSX) Music

### ISSUE THREAD

**Issue by leop2p** [vgmtrans/vgmtrans#557]
Could you please add support for this game in order to extract the music? In game's folder I have imported all files to program, but there's no music detected escept VH and VB files. But it doesn't contain any music. What format should I import to get the music from that game?

I uploaded the game archive without ***.STR** and ***.XA** files.
https://mega.nz/folder/fgcyEZzb#v_xGTx7OZgA6RhBxyv8__g

Please help.

**Comment by mikelow** [comment]
The app does not support streamed formats and the git Issues should not be used as a help forum.
