### ISSUE TITLE
Quintet SPC rips looped section incorrectly (Terranigma Underworld)

### ISSUE THREAD

**Issue by jimbo1qaz** [vgmtrans/vgmtrans#57]
Terranigma Underworld theme (https://www.youtube.com/watch?v=S3mqIDAVObA)

According to vgmtrans hex view, the SPC has two sections: intro and loop.

The first note of the looped section, and the note properties of the second note (possibly also first), are corrupted.

Track 2 (bass): The first note has a velocity of 12 and is inaudible.

Tracks 2 and 7 are slightly behind, and track 3 is severely behind. EDIT: This is because noteProperties indicates an excessive delay between the first and second notes.

(Precompiled interim-20151012 fd76704)

**Comment by StarWolf3000** [comment]
Support for Quintet games is currently work in progress (check recent commits and my comment on 150763ddb6a4e6af36e69450fd709fbe434b9448). So please be patient.

**Comment by jimbo1qaz** [comment]
I understand. The last version of vgmtrans I used had no support, and it was released a few weeks ago. Is this bug report helpful or useless?

**Comment by loveemu** [comment]
@jimbo1qaz Thanks! I appreciate your report very much. This issue happened due to a simple misunderstanding.

**Comment by jimbo1qaz** [comment]
will test soon... maybe
