### ISSUE TITLE
SNES RARE Battletoads-Double Dragon support for samples / playback / sf2

### ISSUE THREAD

**Issue by ReaperMantis** [vgmtrans/vgmtrans#570]
**Is your feature request related to a problem? Please describe.**
SNES RARE Battletoads-Double Dragon spc format does not appear to be fully supported.  VGMTrans is able to detect sequences and RAREsnes, but does not detect the Samples or Instrument Sets and is unable to play back the SPC files.
The same SPC files are able to be played back successfully in other SPC players.

**Describe the solution you'd like**
It would be great to be able to support this format fully for playback and sample / instrument set extraction for SF2 files to go with the MIDI files.

**Additional context**
According to [VGMPF](https://vgmpf.com/Wiki/index.php?title=Super_Famicom/Super_NES_Sound_Driver_List#Rare_.7E_Chris_Stamper.2C_Mark_Betteridge), some RARE games each have their own unique implementations for their sound drivers.

**Comment by mikelow** [comment]
This is not a bug, but a feature request.

**Comment by ReaperMantis** [comment]
My apologies, is there an appropriate place to make a feature request?

The issues section has the template for "New feature or format support request", so I thought it was the correct place.

**Comment by KungFuFurby** [comment]
I see you posted over in the Discussions section, but I'll redirect you to [the discussion page you created](https://github.com/vgmtrans/vgmtrans/discussions/571) since you also posted here first. I have some tracing-related notes for you over there comparison-wise with Donkey Kong Country.
