### ISSUE TITLE
PSF2 to MIDI/DLS

### ISSUE THREAD

**Issue by Baleoce** [vgmtrans/vgmtrans#58]
First of all, thanks a ton for fixing the Square PSF2 decoding. I can finally play FFXI music in VGMTrans now which is great. The problem I'm having now is that when I convert a track to MIDI/DLS, and then load it into any sound font player like fruityloops, the midi is intact (I think), but the soundfonts still aren't right. I guess all I've ever wanted to do was be able to single out PSF2 and miniPSF2 channels so that I can sequence them myself in a DAW and do arrangements / remixes. No PSF2 player out there to my knowledge supports channel muting though, hence why I'm trying to go about it using this method. I'm not sure what to do about it tbh, or whether it's something that is even fixable on your end. It might just be some weird midi issue. Anyway, thanks again for your continued support of this program, it's very much appreciated! 

- Bale

**Comment by StarWolf3000** [comment]
This is not just with PSF, but with most Formats supported. DLS files are NOT Soundfonts, but they are similar. DLS support is limited in most applications, they tend to use the SF2 specification instead. Export the song(s) as MIDI and SF2 instead and check, if they are tuned correct.

There is the possibility to convert between DLS1/2 and SF2, but that can cause detune of the instruments and loss of articulation/envelope data. DLS1/2 is only recommened for Modplug Tracker/OpenMPT, all other MIDI renderers/players work best with SF2.

**Comment by apollolux** [comment]
One thing I've found to check is if VGMTrans is saving the *sequence* as a MIDI with more than 16 tracks. Remember that GM supports only 16 channels (for safety; ignore the fancy MIDI specs for a moment), and when VGMTrans saves anything more it goes back to 1. Also check what patches the instruments are saved to; I've had many conversions where Strings are put in Piano program numbers, Trumpet in Organ, etc.

Personally, I've found some MIDIs generated by VGMTrans from Final Fantasy X tracks have up to 24 channels used at once, so in a MIDI sequencer I manually reassigned channels and instruments as needed, and combined percussion tracks as well, in order to get songs sounding "like they're supposed to," and also edited the resulting DLS or SF2 to correct badly assigned patches.

**Comment by mikelow** [comment]
Problem is vague. Unclear if vgmtrans is at fault. Closing.

**Comment by moronilds** [comment]
How do I get psf and psf2 files? I drag & drop a PS2 or a PS1  iso to VGMTrans and the only thing that appears is VGMSampColl and when appears some VAB I can save it as SoundFont or DSL, but as a midi sequence. I need to know if I just have to drag & drop an ISO or I gotta get these psf / psf2 files first.

**Comment by Fedexer1** [comment]
> How do I get psf and psf2 files? I drag & drop a PS2 or a PS1 iso to VGMTrans and the only thing that appears is VGMSampColl and when appears some VAB I can save it as SoundFont or DSL, but as a midi sequence. I need to know if I just have to drag & drop an ISO or I gotta get these psf / psf2 files first. Or maybe the problem is that I use Windows 10 and not MAC.

You search for the game on the search bar here. Example: https://www.zophar.net/music/search?search=final+fantasy+x

After you choose one game you click on "Download original music files". Extract the zip. Drag a single .psf file into VGMTrans and then you extract the midi from the Sequence and Soundfont from Instrument Set

**Comment by moronilds** [comment]
"Download Original Music Files" I don't see this option. The game I'm
trying to extract midi sequence is STREET FIGHTER ALPHA 3, ARCADE OR PS1
VERSIONS.



Em ter, 14 de abr de 2020 06:45, Fedexer1 <notifications@github.com>
escreveu:

**Comment by StarWolf3000** [comment]
@moronilds This game does not use MIDI sequenced music. It uses streamed music in EA's XA audio format. Which means there are no PSF files.

**Comment by piratesephiroth** [comment]
The arcade game does use CPS2 sequenced audio.

**Comment by StarWolf3000** [comment]
@piratesephiroth If there's a music dump from MAME, then it probably can be used, since vgmtrans has a MAME loader, otherwise you're out of luck.
