### ISSUE TITLE
Cannot export certain instrument sets to .dls or .sf2

### ISSUE THREAD

**Issue by sykhro** [vgmtrans/vgmtrans#59]
For example, a DLS or SF2 from FFIX won't save

**Comment by imyoutubefan2** [comment]
Yep. Files from Kingdom Hearts 2 won't save at all either. When saving to a sf2 or dls nothing exports. Not even a blank file. No error either.

**Comment by sykhro** [comment]
Odd, I can export from KH2 just fine; the instruments don't match perfectly but almost

**Comment by jimbo1qaz** [comment]
psf: chrono cross - time of the dreamwatch

Saved SF2 sounds wrong. Internal playback is OK.

**Comment by mapsico** [comment]
Had this problem for .psf2lib files.
With PSF2 archives simply containing .pfs2 files, the soundfont can be extracted by dropping them in vgmtrans window.
For (some?) archives containing a .pfs2lib file, dropping it in the window works and vgmtrans displays all tracks. However, trying to export .hd to .sf2 redults in nothing happening. The only soundfont which can be extracted is the soundfont corresponding to the very first track in the file. Trying this with other tracks just yields this precise soundfont. Weird...

**Comment by Boyfinn** [comment]
If you look at the Akao instrument set data, you can see that each instrument still has some unknown data in them, thus they cannot be exported to a soundfont.
I've been trying to crack the format for a while now, but i can't seem to find anything pointing towards looping points in a sample.

**Comment by M0DSteam** [comment]
There's The Case Of Pokemon HeartGold And SoulSilver, With The GB Sounds Soundfont, BANK_GAMEBOY, If You Try To Play a Song Which Uses This Bank, To Convert To DLS Or SF2, The Program Just Hangs And Says "VGMTrans Stopped Working" But If I Try To Just Export On Original Format It Actually Works, But It Has No Actual Format...

**Comment by jimbo1qaz** [comment]
Why Do You Capitalize Every Word? It Looks Weird.

**Comment by TekraGit** [comment]
> Yep. Files from Kingdom Hearts 2 won't save at all either. When saving to a sf2 or dls nothing exports. Not even a blank file. No error either.

What I did was load the bgm file AAANNNDD the corresponding wd files in VGMTrans. You have to load the music AND the corresponding wd files for it to work.

For example: Load music054.bgm and then load the corresponding wd which is wave0054.wd. Only after can you export to dls and sf2. 

Tips: If you click on music sequence for "music054.bgm", you'll see the header. Click on it until you find the associated wd ID which will be in hexadecimal. It will show up as "36 00". It is a two byte but we only need the first byte, "36". Now convert that to decimal you should get 54 in decimal. You'll need to do this for some songs in KINGDOM HEARTS 2. Just in case your brain tricks you into thinking you got the right number after converting it in your head.

So now we have 54; load in "wave0054.wd". Afterwards you can then right click on it and export to DLS and SF2 successfully.

Hope this helps
