### ISSUE TITLE
Not beginner-friendly

### ISSUE THREAD

**Issue by XaikuTheMaverickHunter** [vgmtrans/vgmtrans#63]
Is there any way that you could upload a video tutorial or something on how to get the latest version of VGMTrans working? I still have Windows XP, by the way.

**Comment by robotortoise** [comment]
Huh? It's really, REALLY user friendly. You just have to go to the Releases tab and download the latest build from there, then run the executable. It has pretty GUIs and stuff.
I don't know if it'll work on XP, though.


Unless you want the latest LATEST build, which you'd have to build yourself.

**Comment by XaikuTheMaverickHunter** [comment]
Actually, that's the problem. I don't know how to build it, and I'm not sure which version (among those that don't need building) is the latest. Do you know which one it is?

**Comment by robotortoise** [comment]
Ah, I see. The latest version is simply the one that's on the Github page.

[VGMTrans_WTL.zip](https://github.com/vgmtrans/vgmtrans/files/200595/VGMTrans_WTL.zip)


Here's a compiled build of the latest version.

**Comment by XaikuTheMaverickHunter** [comment]
Thanks a metric-crud-ton! Seriously. The reason I needed the latest version is because I was trying to get sounds from the raw WD files used in the first Kingdom Hearts (particularly the WD file used when Sora's shadow comes out of the floor and becomes the Darkside in the beginning of the game), and I have them now.
