### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by SirSoundfont** [vgmtrans/vgmtrans#64]
For a long time, I've been trying to create a Kingdom Hearts soundfont, but when I open the file in VGMTrans, it stops responding for a few minutes, and then crashes. I have no trouble with DS ROMs, but PS2 ISOs seem to not work.

**Comment by sykhro** [comment]
You can use a .psf2 rip of the song you need. Zophar Domain has plenty

**Comment by sykhro** [comment]
ISO files are not supported, please use .psf(2) or the game files directly
