### ISSUE TITLE
Linux QT - save midi and sf2? right-click menus?

### ISSUE THREAD

**Issue by jimbo1qaz** [vgmtrans/vgmtrans#66]
right now, linux qt only supports "playing" songs. (also, it doesn't work).

how do you save a midi+sf2? it's not hooked up to the gui?

**Comment by sykhro** [comment]
That's not implemented yet.
I've tried the qt version and it seems quite broken from the audio-playing perspective compared to the WTL builds. Probably because of fluidsynth not being fully tweaked yet

**Comment by kerbingamer376** [comment]
I'd also like to export midis, and it doesn't seem to be in the gui, or right-click menus are missing.

**Comment by mikelow** [comment]
Yep, the Qt version is currently very incomplete. It is known.
