### ISSUE TITLE
The OS X version of vgmtrans is broken

### ISSUE THREAD

**Issue by SamusAranX** [vgmtrans/vgmtrans#67]
I get that it's a WIP, but there's not even a real app in there:
![screen shot 2016-07-08 at 23 46 48](https://cloud.githubusercontent.com/assets/676069/16702488/a55b6704-4566-11e6-84b4-dfe83fad733d.png)

Is the OS X version being maintained by anyone?

**Comment by sykhro** [comment]
This is the Qt version, which is the same across all platforms, and it's pretty broken. 
On Windows, it doesn't output sound correctly

**Comment by mikelow** [comment]
Sure is.
