### ISSUE TITLE
Keyboard Controls For VGMTrans Mac

### ISSUE THREAD

**Issue by JPS46225** [vgmtrans/vgmtrans#69]
Hi

I'm trying to work out how to use VGMTrans on an iMac.

So far, I've worked out that the space bar plays the files.

However, I don't know how to extract the MIDI sequence files using the keyboard.

Is there a file in the source code that I can use as reference?

Thanks

**Comment by sykhro** [comment]
Besides playback, nothing is implemented in the Qt version afaik

**Comment by JPS46225** [comment]
Ok, one other question. I'm trying to work out what was needed to make VGMTrans possible.

E.g.: Probably some reverse engineering...

**Comment by sykhro** [comment]
Tons of reverse engineering for sure. The code needs some cleanups though, after 700 commits and counting things have gotten confused
