### ISSUE TITLE
Debug build hangs (or very slow) when loading DS ROMs

### ISSUE THREAD

**Issue by jimbo1qaz** [vgmtrans/vgmtrans#71]
When I load DS roms, vgmtrans builds a list of detected music files. The left side "Detected Music Files" scrollbar shrinks (indicating more overflowing items). The debug build starts out fairly quickly, but the scrollbar quickly stops moving as the number of items increases. VGMTrans temporarily hangs when loading SM64DS (16MB, smallest ROM I have), or hangs for much longer with Spirit Tracks (128MB, much larger).

The release build doesn't have polynomial/exponential/slow runtime when loading "Detected Music Files".

**Comment by sykhro** [comment]
Debug mode means a lot more things are checked and zero-initialised at runtime; unfortunately the NDS parser has lots of operations on vectors, and with debug mode activated those eat lots of cpu time. I don't think it's solvable without a solid rewrite of the VGMItem class (which should happen sometime soon anyway)
