### ISSUE TITLE
CTR Tracks only export broken sound files and a Sequence

### ISSUE THREAD

**Issue by Harley201** [vgmtrans/vgmtrans#74]
CTR uses a custom made psf which makes it quite hard to extract, I have gotten one or two ok samples but the rest is ether ear rape or nothing, I would love for someone to make some sort of exporter or export feature for CTR because in my opinion the music for CTR is amazing and I don't really see any vgm love or people exporting models or files which is kinda sad

**Comment by Harley201** [comment]
EDIT: Nvm they actually don't export sequences, just broken audio

**Comment by Harley201** [comment]
If anyone doesnt know CTR is Crash Team Racing for the ps1...... just in case

**Comment by mikelow** [comment]
Guessing this is an unsupported format.
