### ISSUE TITLE
Blank UI

### ISSUE THREAD

**Issue by Aesulus** [vgmtrans/vgmtrans#75]
I built the Qt version by following [Building the WIP QT version of VGMTrans for 64 bit Windows](https://github.com/vgmtrans/vgmtrans/wiki/Building-the-WIP-QT-version-of-VGMTrans-for-64-bit-Windows) to the letter after cloning https://github.com/vgmtrans/vgmtrans/commit/098793f3aee63d5becfcc37857a3bb5c4954d440, which is (at the time of writing) the latest commit. However, running the compiled EXE only shows a blank gray interface with a few working movable dividers but no content. Is anyone else having the same problem?
![image](https://cloud.githubusercontent.com/assets/8322422/18703864/bc6c021c-7fb5-11e6-83e7-942bd6817c38.png)

**Comment by sykhro** [comment]
This is known, and it's not a "problem". Qt is WIP, you can drag things in it and play them back by pressing space. Playback is broken and you can't actually export anything.

**Comment by mikelow** [comment]
Yeah... sorry to disappoint.
