### ISSUE TITLE
Qt version - Crashes when playing back song

### ISSUE THREAD

**Issue by CaptCatfish** [vgmtrans/vgmtrans#76]
I am trying to play back a .sfc file but every time I try to do that, it crashes.  Is this a bug with the software or an error on my end when compiling?

**Comment by StarWolf3000** [comment]
SFC stands for "Super FamiCom" (Super Family Computer, the japanese SNES). These aren't song files but the actual games (dumps of western releases are .smc instead).

Loading complete SFC/SNES ROMS is currently not supported, only already dumped SPC (.spc) songs. You can dump them with special hardware or in most emulators. A huge collection is already available at snesmusic.org.

VGMTrans can load most of these .spc files, play them and export MIDI files with SF2/DLS banks.
