### ISSUE TITLE
Ps1 "VAB" Instrument Set conversion to SF2 doesn't make a .SF2 file

### ISSUE THREAD

**Issue by SirSoundfont** [vgmtrans/vgmtrans#78]
I'm trying to get the instruments from "Crash Bandicoot 2: Cortex Strikes Back" for PS1, and it has 2 instrument sets, both called "VAB". I've tried converting them to SF2, and no file is created. I tried making a DLS file from them, and they don't create one. Are they just empty instrument sets, or are they not supported by VGMTrans yet?

**Comment by SirSoundfont** [comment]
Update: I was able to extract the instruments from Crash 2 using WinRAR and PSound, but I still don't know why the "VAB" instrument set doesn't make a soundfont file when I click "Convert to Soundfont 2".

**Comment by Harley201** [comment]
you should use Crash Edit for Crash Bandicoot 2 instruments

**Comment by Harley201** [comment]
also use it for Crash Bandicoot 3

**Comment by waffleoRai** [comment]
I cannot convert VAB files to DLS or SF2 either using VGMtrans, for what it is worth. Same problem - I click it, but nothing happens. The code to read VAB files and write SF2 is all there, but I'm not sure if the actual conversion is working. If you're good with C++, it might be possible to use the existing code to whip up something new.

**Comment by SirSoundfont** [comment]
I haven't learned much C++, I'm better with C#, but it isn't that big of an issue to me. I can use other soundfonts. Still, if anybody knows why it isn't working, I would like to know.

**Comment by Harley201** [comment]
A lot of ps1 games contain custom music formats, Crash Bandicoot 2 has some custom songs same with Crash 3, Crash Bash and Crash Bandicoot 1. CTR is completely custom and people are still unable to figure out the samples and the sequence. Like I said before if you want Crash Bandicoot 1-3 samples or sequences use CrashEdit
