### ISSUE TITLE
Conversion of PSX VAB articulation / envelope parameters

### ISSUE THREAD

**Issue by waffleoRai** [vgmtrans/vgmtrans#83]
Hello!

It seems that vgmtrans, for whatever reason, is not writing PSX VABp sound bank files to SF2 (or DLS). As someone else reported, right clicking the bank and selecting "convert to SF2/ DLS" does nothing.

I decided to write my own converter from scratch using your source code as reference (don't worry - it's for personal use only), however, I am not confident that my ADSR conversion is entirely accurate. That, and I don't even know where to begin with volume, pan, vibrato, reverb, and portamento. Honestly, I can add a lot of those back manually, but I'd like to transfer at least the ADSR as accurately as possible.

The reason I am suspicious of my values is that the "time in seconds" is coming out extremely enormous in some cases. For instance, a release time of 61799.7928 seconds seems rather... impractical. I also note that an attack that is stored as "0" in the VAB (the seven bits to denote attack rate are all 0) produces an attack time of 1780874.0327 seconds (with Am = 1). Is that supposed to happen? Did I interpret something incorrectly? Am I just to assume 0 means 0?

My short term fix is going to be tossing any 0's or time above 20 seconds, but I don't know what good that'll do if the ADSR values are all being converted to something hilariously outside the ballpark to begin with.

On the other hand, the VAG decompression algorithm works like a dream!

Thank you!

**Comment by paulsapps** [comment]
Maybe this helps: https://github.com/paulsapps/alive/blob/dev/src/oddlib/audio/Soundbank.cpp#L11

**Comment by waffleoRai** [comment]
Yeah! Thanks!
