### ISSUE TITLE
File operation improvements

### ISSUE THREAD

**Issue by MugUK** [vgmtrans/vgmtrans#84]
Would it be possible to do a bulk extract, e.g. every tune from an NDS game into .MID & .DLS format? Instead of having to right-click and export each tune one after the other.

Also an ability to rename the files within the window as some have random characters and can't be exported.

**Comment by mikelow** [comment]
1) Agreed, this would be a good feature. 
2) Can you give an example of a rom with with the random character problem?

**Comment by MugUK** [comment]
1. Many thanks - some of the larger Japanese games are a nightmare to rip due to the extra-large number of separate music files embedded within the file.

2. One of the games that I haven't ripped yet due to the foreign characters is "SpongeBob SquarePants - Creature from the Krusty Krab". There are five tunes in there where the filename has random characters appended to them. I could go into the MUSIC.DXE file via WinHex and truncate the filename so that it just leaves the English sounding part, but it would be nice to be able to rename the file within VMTrans.

I've uploaded screenshots of the MUSIC.DXE file being open in VMTrans and they can be found on my Dropbox at the following URLs:

a) https://www.dropbox.com/s/86mc12y9mftzv7e/Spongebob_NDSMusic_ForeignChars1.png?dl=0
b) https://www.dropbox.com/s/qd7azyqz8aehes9/Spongebob_NDSMusic_ForeignChars2.png?dl=0
c) https://www.dropbox.com/s/42q8f0ij45bqp3i/Spongebob_NDSMusic_ForeignChars3.png?dl=0

In previous cases, there was only one file within a music file, so I just renamed it internally via WinHex.

**Comment by sykhro** [comment]
I will be considering this for the Qt port, unsure if anyone wants to bother adding it to the WTL frontend

**Comment by simonmkwii** [comment]
Yeah, bulk extraction to MIDI and SF2 would be fantastic.
It's annoying to do it one-by-one.

**Comment by sykhro** [comment]
The way we manage strings in general needs some work, but I have implemented both features in the qt-port with https://github.com/vgmtrans/vgmtrans/commit/d85ff00f7b3fe7fdccb1ece1b17a33ccf61bcb6a

I will close this because the WTL UI should only be limited to bug fixes and not new features at this point (that's the whole concept of deprecation); I don't think any other dev would be interested in implementing it there
