### ISSUE TITLE
PSX, PSF - AKAO v2 banks/midi support (SquareSoft, Parasite Eve)

### ISSUE THREAD

**Issue by Corak667** [vgmtrans/vgmtrans#89]
Hi, found some psf rips from Parasite Eve, that contain AKAO signature for banks and even for midis. Could format support be added and they be converted to standard midi and Soundfonts? 
Example:
http://coraksoft1.narod.ru/mod/PSF_PlayStation/Parasite_Eve__Yoko_Shimomura.7z

**Comment by mikelow** [comment]
These use an earlier version of the same sound driver. Currently not supported. Need to go back and rewrite the AKAO code; it's some of the first I ever wrote and it is _sloppy_.
