### ISSUE TITLE
Support for Club Penguin: Elite Penguin Force

### ISSUE THREAD

**Issue by pizzaguy14** [vgmtrans/vgmtrans#90]
I usually do a good job extracting the MIDI files from Nintendo DS roms, but there are these two games that won't work properly for some reason. The games are Club Penguin: Elite Penguin Force, and its sequel Herbert's Revenge (they have a good soundtrack trust me). Every time I load up one of the roms for these games, VGMtrans only finds the MIDI files for DGamer (some chat system that Disney bundled with these games). Though, what I believe is happening is that those files may be stored in some kind of bank at the start of the rom, meaning that VGMtrans prioritizes them. Basically, I want to extract the MIDI files from these games, but I can't figure out how to get VGMtrans to detect the proper files.

**Comment by MDHEXT** [comment]
i think all disney games use custom sequence formats. toy story 3 ds only has the music for the d-gamer user interface.

**Comment by Winonamac** [comment]
https://github.com/Olivercomet/EPFExplorer

It used a Custom .xm Format
EPFExplorer is able to extract them if you unpack the game and open music.bin
![image](https://user-images.githubusercontent.com/71861540/124871852-913f5c00-df92-11eb-8746-d1f8447d5ad2.png)

**Comment by sykhro** [comment]
Converting XM to MIDI and DLS is definitely out of scope for VGMTrans (and a very hard thing to do properly).

**Comment by MDHEXT** [comment]
> https://github.com/Olivercomet/EPFExplorer
> 
> It used a Custom .xm Format
> EPFExplorer is able to extract them if you unpack the game and open music.bin
> ![image](https://user-images.githubusercontent.com/71861540/124871852-913f5c00-df92-11eb-8746-d1f8447d5ad2.png)

I believe you can convert to midi by using OpenMPT. as for the samples, you can dump them with OpenMPT, but you'll need to create a soundbank file (sf2, dls) for them yourself using other tools (i.e. polyphone, vienna, awave studio).

**Comment by MDHEXT** [comment]
if your goal is to rip them, you can dump to wav in OpenMPT too or you can get the foobar2000 plugin by kode54.
