### ISSUE TITLE
FAQ: How to read midi+dls/sf2?

### ISSUE THREAD

**Issue by ORelio** [vgmtrans/vgmtrans#91]
Hello,

First of all congrats for VGMTrans which does its extracting job very well (tested on an NDS game)! 👍

However I can't find an easy-to-use software for playing Midi files with custom SoundFont. The various playback methods I could find e.g. in [this article](http://adamrehn.com/articles/playing-midi-soundfonts/) requires setting up the SoundFont before playing every single file. For example with VLC or [SoundFont Midi Player](http://falcosoft.hu/softwares.html#midiplayer) for every file I need to open setting, load the soundfont, then load an play the track, which requires a couple of clicks and don't allow even building a playlist since each track requires a different SoundFont. (Actually there seems to be a "SoundFont" column in SFMP playlist, so it seems to support one different SoundFont per midi file, but the font is not used when playing the file...)

So the questions about midi+dls/sf2 are:
- Is there any user-friendly way of playing back midi+dls/sf2?
- It possible to convert midi+dls/sf2 to some [module file](https://en.wikipedia.org/wiki/Module_file) (standalone file with both track _and_ samples)?
- Or, at least, how can I render a .wav file from midi+dls/sf2 for convenient playback?

Thanks for any help you can provide :)

**Comment by Corak667** [comment]
Hi, you can use XMPlay of Foobar2000 on midi, and it's midi plugins. Your soundfont need to be the same filename as midi file. or if there is single bank used per many midi files, you could use "[check for partial match" option](http://picsee.net/upload/2017-03-10/765f3d8052bc.png) in XMplay, so naming them like "Doom.sf2" and midi files for example: "Doom_01.mid", "Doom_Hell.mid", "DoomGuy.mid" - this soundfont will be automatically used.

If you need to rework it as tracker module - just import them to OpenMPT, but for me it's still very far from normal midi+sf2 sequencing and modules importing, so better to use them separately.

Also there is Awave Studio project - best soundfont editor ever. You can rework whole collections or single instruments. (Still it's propietary and not free, so have some seriour limitations).

**Comment by MugUK** [comment]
I wrote a tutorial (several years ago now), using an older version if VGMTrans, Awave Editor (MID+DLS > RMI > OpenModPlug. It worked for 90% of the titles I ripped. It probably needs an overhaul if Awave isn't needed any more as part of the process though.

Would the old one be of any use?

**Comment by ORelio** [comment]
To be honest, I have no particular knowledge in music composition, and would not be able to actually rework a music piece. Was asking for module conversion mainly for convenience since everything is in the same file and many players can read them, but if this process is not straightforward and alters the compositon, that's not really what I'm trying to do. So thanks for your offer @MugUK but I'm afraid I would not _actually_ benefit from a complete tutorial.

Regarding playback, I could easily setup both XMPlay and Foobar2000 with midi plugins and both perfrom well and automatically load the appropriate sound fonts... thank you @Corak667! After tinkering a bit with XMPlay's abilities, I see it can export tracks as WAVE files if needed, so seems like I've got all the answers I need :)

Keep up the good work and thanks for your swift responses :+1:
