### ISSUE TITLE
Final Fantasy IX not loading

### ISSUE THREAD

**Issue by Fraggoso** [vgmtrans/vgmtrans#94]
When I drag and drop my FF9.IMG into VGMTRANS, it loads the AKAO files and I can see the detected music files on the lefthand side. 
After that I'm treated with the error message "Alert: referencing an articulation that was not loaded." and vgmtrans crashes.

As the soundeffects are also AKAO files, would it even be possible to convert these appropriate? ^^

**Comment by sykhro** [comment]
Duplicate: #59

**Comment by Fraggoso** [comment]
Oh thanks. I saw the #54 but thought it would be another problem. ^^
