### ISSUE TITLE
Error building on Mac OS X Mavericks

### ISSUE THREAD

**Issue by apollolux** [vgmtrans/vgmtrans#96]
I get the following error trying to build on Mavericks using the "Building the WIP QT version of VGMTrans for OS X" automated build instructions:

> airlux:build lux$ cmake ..
>-- PREFIX PATH: /Users/lux/dev/app-dev/vgmtrans/contrib/x86_64-apple-darwin11
>CMake Error at CMakeLists.txt:72 (find_package):
>  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
>  has asked CMake to find a package configuration file provided by
>  "Qt5Widgets", but CMake did not find one.
>
>  Could not find a package configuration file provided by "Qt5Widgets" with
>  any of the following names:
>
>    Qt5WidgetsConfig.cmake
>    qt5widgets-config.cmake
>
>  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
>  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
>  "Qt5Widgets" provides a separate development package or SDK, be sure it has
>  been installed.
>
>
>-- Configuring incomplete, errors occurred!
>See also "/Users/lux/dev/app-dev/vgmtrans/build/CMakeFiles/CMakeOutput.log".

Qt 5.6 from Qt installer installed on Mavericks 10.9.5. Downloaded git repository 2017-07-09 at 6:26pm Eastern Time.

Edit 1: Setting CMAKE_PREFIX_PATH to the clang_64 directory of this particular 5.6 install moves past it, but apparently can't find FluidSynth.

>airlux:build lux$ cmake .. -DCMAKE_PREFIX_PATH=/Users/Shared/Qt5/5.6/clang_64/
>-- PREFIX PATH: /Users/Shared/Qt5/5.6/clang_64//Users/lux/dev/app-dev/vgmtrans/contrib/x86_64-apple-darwin11
>-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.5") 
>CMake Error at /usr/local/Cellar/cmake/3.2.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
>  Could NOT find FluidSynth (missing: FLUIDSYNTH_LIBRARIES
>  FLUIDSYNTH_INCLUDE_DIR)
>Call Stack (most recent call first):
>  /usr/local/Cellar/cmake/3.2.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
>  cmake/FindFluidSynth.cmake:22 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>  CMakeLists.txt:92 (find_package)
>
>
>-- Configuring incomplete, errors occurred!
>See also "/Users/lux/dev/app-dev/vgmtrans/build/CMakeFiles/CMakeOutput.log".

Installing FluidSynth via Homebrew gets past this, but then a new error about variables not found:

>airlux:build lux$ cmake .. -DCMAKE_PREFIX_PATH=/Users/Shared/Qt5/5.6/clang_64/
>-- PREFIX PATH: /Users/Shared/Qt5/5.6/clang_64//Users/lux/dev/app-dev/vgmtrans/contrib/x86_64-apple-darwin11
>-- Found FluidSynth: /usr/local/lib/libfluidsynth.dylib  
>-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
>-- Found GLIB: /usr/local/Cellar/glib/2.52.3/include/glib-2.0;/usr/local/Cellar/glib/2.52.3/lib/glib-2.0/include (found version "2.52.3") 
>CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
>Please set them or make sure they are set and tested correctly in the CMake files:
>INTL_LIBRARY
>    linked by target "vgmtrans" in directory /Users/lux/dev/app-dev/vgmtrans
>QCOCOA_LIBRARY
>    linked by target "vgmtrans" in directory /Users/lux/dev/app-dev/vgmtrans
>QT5PRINTSUPPORT_LIBRARY
>    linked by target "vgmtrans" in directory /Users/lux/dev/app-dev/vgmtrans
>QTPCRE_LIBRARY
>    linked by target "vgmtrans" in directory /Users/lux/dev/app-dev/vgmtrans
>
>-- Configuring incomplete, errors occurred!
>See also "/Users/lux/dev/app-dev/vgmtrans/build/CMakeFiles/CMakeOutput.log".

It's at this point I decided to switch to building manually, which generated vgmtrans.app in the build directory. Opening it results in the error _You can't open the application "vgmtrans.app" because it may be damaged or incomplete._ , no app icon in the Contents directory, and the Contents/MacOS directory inside is empty.

**Comment by sykhro** [comment]
I'll save you the hassle of building; the qt version only has playback implemented.

**Comment by sykhro** [comment]
Closing this, since the qt-port branch builds correctly on OS X. Please add a comment to #121 if you run into similar issues
