### ISSUE TITLE
Certain files usually crash upon opening, but sometimes they don't

### ISSUE THREAD

**Issue by SirSoundfont** [vgmtrans/vgmtrans#97]
If I attempt to open a file in VGMTrans, and it doesn't work, if I keep trying to open it, it eventually works. This seems to only work about 5% of the time. It only happens with specific files, and this happens across all versions of VGMTrans that I've used.

**Comment by sykhro** [comment]
This information is not of any help. Please describe the desired behaviour vs. what happens when you report an issue.
