### ISSUE TITLE
VGMTrans won't load music files

### ISSUE THREAD

**Issue by Jerlewr** [vgmtrans/vgmtrans#99]
I've tried .psf files and .mini2sf files and they won't load or open. Is there any way to fix this? Dropping the files into the windows does nothing and clicking the "Open" button does nothing.

**Comment by sykhro** [comment]
Be sure to have the .psflib along with the files.
Also, what game?

-------- Original Message --------

**Comment by Jerlewr** [comment]
Thank you for the fast response. The .psf files were of Ape Escape and the .mini2sf files were from Super Mario 64 DS. How do I get .psflib along the files?

**Comment by sykhro** [comment]
They should be included along with the files. Please extract the *entire* archive those files came in and try again.

**Comment by Jerlewr** [comment]
Sorry for another question, but I have the .psflib files, but I do not know what to do with them. Do I somehow attach them to .psf files?

**Comment by sykhro** [comment]
They need to be in the same folder as the psf. vgmtrans will look for them on its own.

**Comment by Jerlewr** [comment]
Do I put the folder in a vgmtrans folder or?

**Comment by sykhro** [comment]
Put the psf and psflib in the same folder, any folder is fine. Then load the psf in vgmtrans. It should work.

**Comment by Jerlewr** [comment]
Sorry but putting the psf in vgmtrans isn't working.

**Comment by sykhro** [comment]
But are the psf and psflib in the same folder? It's crucial.

-------- Original Message --------

**Comment by Jerlewr** [comment]
Yes they are. https://imgur.com/a/LzVVJ

**Comment by sykhro** [comment]
It could be that this game format is not supported. I'll look into it when I can

-------- Original Message --------

**Comment by Jerlewr** [comment]
Just coming back here to say that I got it to work! The case is finally closed!

**Comment by sykhro** [comment]
Phew, one thing less on the list then. Please close the issue properly.
